(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.kv = function() {
	this.initialize(img.kv);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,640,960);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.white_bg = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("A8HGQIAAsfMA4PAAAIAAMfg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.white_bg, new cjs.Rectangle(-180,-40,360,80), null);


(lib.s6_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1E2946").s().p("AgYArQgMgGgGgMQgIgMABgNQgBgNAIgLQAGgMAMgHQALgGANAAQAOAAALAGQALAHAHAMQAIALgBANQABANgIAMQgHAMgLAGQgLAHgOAAQgNAAgLgHgAgPgcQgJAFgEAHQgFAIABAIQgBAJAFAIQAFAIAIAEQAHAEAIAAQAOAAAJgJQALgKgBgOQAAgIgEgIQgFgHgHgFQgIgFgJAAQgHAAgIAFg");
	this.shape.setTransform(10.45,16.425);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#1E2946").s().p("AiHCRIgDgJIgEgHQAtgGAlgIQAngIAjgQIABgBIgDgDIgjgdIAVgMIAjAcIAFAEQAVgLARgPQATgQAMgUIhaAAQgSAPgWANQgZAQgmAPIgEgHIgLgMQAigMAagPQAagPAUgRQASgQANgSIAbAGQgJANgNANIBRAAIAFgCIAQAKQgSAlgcAZQgdAbgkARQglARgpALQgvALgnAEIgDgHgAiHAKIgGgKQAcgFAigKQAagJAXgLIgDgCQgIgIgJgGIgTgMIASgNQAMAHAQALIAPAMQAVgNAUgQQANgLAKgOIhcAAIgFAFQgfAYgpATIgLgNIgHgEQAZgLAYgOQAWgPAQgOQAQgNALgPIAbAFIgVAYIBVAAIAEgBIARAKQgRAcgYAVQgZAXgeARQgeARghAKQgeALgkAIQgBgGgEgGg");
	this.shape_1.setTransform(-11.375,6.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#1E2946").s().p("AiNCIIgEgIIgGgGQApgIAXgKQANgFALgGIgBAAQgYgSgRgcIAWgJQAQAZAVAPIADABQAMgLAGgMQAGgKACgLIhiAAIAAh/IBnAAIAAgcIiFAAIAAgWIEeAAIAAAWIiBAAIAAAcIBtAAIAAB/IhxAAQgDASgGANQgHAOgMAMQAMAFANAEQAeAJAkADQAgADAxACIgHALQgDAIAAAFQg0gCgggFQgmgEgegLQgQgFgOgHQgOAIgQAHQgdANglAHIgFgHgAAMgEIgBATIBVAAIAAghIhUAAgAhbAPIBOAAIABgUIAAgNIhPAAgAAMgmIBUAAIAAghIhUAAgAhbgmIBPAAIAAghIhPAAg");
	this.shape_2.setTransform(-46,7.775);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#1E2946").s().p("AiKCUIgNgHQALgSAFgVQAFgUACgWIABhlIgHAJIgFgEIgNgKQARgSAOgdQANgcAIgfIAWAGIgHAYIAtAAIAEgBIAPAJQgDAJgGANIgKAVIgCADIAjAAIAADAQAAAFgCAHQgDAGgEACQgFACgJABIgUACIgDgMQgBgFgDgFIAQAAIAIAAQAFAAAAgEIAAgyIgeAAIAAA9IgSAAIAAg9IggAAIgCAPQgEATgFAPQgFARgJANgAg6A1IAeAAIAAgsIgeAAgAhqA0IAAABIAeAAIAAgsIgeAAgAg6gIIAeAAIAAgoIgeAAgAhqgIIAeAAIAAgoIgeAAgAhthEIAsAAIAGgMIAIgTIABgDIgrAAQgJAWgHAMgABICXIAAg/IhDAAIAAgXIBDAAIAAgnIglAAQgGAQgKAPIgNgHIgGgDQALgPAHgSQAIgUADgUIAWAEIgIAaIAdAAIAAgeIAXAAIAAAeIAyAAIAAAWIgyAAIAAAnIA6AAIAAAXIg6AAIAAA/gAAFghIgHgIQATgIALgOQALgNAFgQIAGgWIgtAAIAAgVICLAAIAAAKIgDAsQgCATgCAIQgDALgDACQgEAEgDABQgDACgIABIgOAAIgUAAIgCgLIgEgKIAeABIAGAAQAAAAABAAQAAAAABgBQAAAAAAAAQABgBAAAAQADgDABgIIAFgwIgxAAIgGAcQgHAUgNAQQgNAQgWAKg");
	this.shape_3.setTransform(-80.525,6.95);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#1E2946").s().p("AhJB/IgGgNIAwABIAMAAQAGAAACgCQACgBAAgFIAAibQANgGARgMQARgKAOgLIAbgXIADgDIjUAAIAAgYIDsAAIAGgCIATAPQgOAPgWATQgVASgXAPQgTANgQAJIAACPQAAALgEAHQgEAGgJAEQgKACgQABIgqABg");
	this.shape_4.setTransform(-112.625,8.125);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#1E2946").s().p("AAKBgIAMgSIB6AuIgNAVgAiDCLIgLgPQAkgGAWgIQAZgJANgIQAPgJAGgKQAHgKACgHQACgKAAgHIAAgfIAaAAIAAAfQAAALgDALQgDALgHALQgIALgPALQgQAMgZAJQgZAKglAIIgEgGgAhxBXIAAh4IDmAAIAAB2IgaAAIAAhgIiyAAIAABigAhmhAIAAhQIDOAAIAABQgAhMhVICZAAIAAglIiZAAg");
	this.shape_5.setTransform(54.75,-31.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#1E2946").s().p("AiMCNIgLgKQAigRAYgYQAYgZAOgaQAPgbAIgcQAIgbAEgaQAEgeAAgRIABgiIAbAAIgBAmIgBALIACAOQACARAFAVQAFAWAKAZQAJAWAQAbQAQAZAXAVQAXAWAfAOIgKAKIgIAKQghgPgXgXQgWgVgSgcQgPgZgKgcQgIgUgFgUIgHAaQgIAbgRAfQgPAcgZAaQgXAYgkAUg");
	this.shape_6.setTransform(20.225,-32.725);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#1E2946").s().p("AiCCSIgNgLQAPgOAKgVQAKgUAEgSQAEgPABgQIgsAcIgJgXIAcgPIAbgOIABh0IB0AAIgDgLIgKgaIAZgGIAKAaIAFARIBqAAIAAAWIjhAAIgCByQgCAWgFAXQgFAUgLAXQgKAUgSASIgFgHgAgSCMIgGgLIAwAAQAEAAABgCQABAAAAAAQAAgBAAAAQABgBAAgBQAAAAAAgBIAAhvQAOgGAQgJQANgIAQgNIAFgDIiSAAIAAgWICqAAIAGgCIARAOIgdAYQgRANgRAJIgXANIAABmQAAAKgDAGQgDAGgJACQgIADgOAAIgiABIgDgMgAiUhOIATgJIAgA6IgUALg");
	this.shape_7.setTransform(-10.025,-32.75);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#1E2946").s().p("AiNCIIAAkQIETAAIAAAZIj6AAIAADgIECAAIAAAXgABHBWIgfgbIgZgTIgIANQgKAPgWAOQgVAOgjAMIgHgKIgJgJQAkgLASgLQAUgNAJgMQAJgNADgMIhgAAIAAgVIBiAAIAAgGIAAgqIgyAAQgNASgOAMIgVgOQASgNAMgRQAOgUAHgTIAYAGQgGAOgHAMICVAAIAAAVIhYAAIAAAqIAAAGIBmAAIAAAVIhoAAIgBACIABgBIBAAzQAPANALALIgRAQQgLgLgOgMg");
	this.shape_8.setTransform(-43.65,-32.45);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#1E2946").s().p("AA1CQIgGgSIA1ABQAGAAABgCQABgCABgEIAAi8IjZAAIAADdIgYAAIAAj1IBaAAIAGgMIAJgYIAGgWIAeAFQgFAOgKAWIgJARICVAAIAADUQAAALgEAIQgDAHgJADQgIACgRABIgmABIgCgIgAhBBrIAAiEICBAAIAABsIhqAAIAAAYgAgqA8IBSAAIAAg/IhSAAg");
	this.shape_9.setTransform(-78.35,-32.725);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#1E2946").s().p("AgZCYIAAidICWAAIAACBQAAAKgCAFQgEAGgGACQgGACgMABIgeABIgCgLQgCgGgDgFIAlABQAHgBgBgFIAAgXIhmAAIAAAzgAgBBTIBmAAIAAgbIhmAAgAgBAmIBmAAIAAgZIhmAAgAhrCLIgJgOQAFgDAFgHQAFgHAAgLIAAh4IgyAAIAAgYIBKAAIAACNIAjgaIADALIAFAKIg2AqIgKAJIgGAGgAgwgYIAAgUIBVAAIAAgWIhDAAIAAgTIBDAAIAAgVIhLAAIAAgTIBLAAIAAgaIAZAAIAAAaIBQAAIAAATIhQAAIAAAVIBFAAIAAATIhFAAIAAAWIBaAAIAAAUgAhdhdIgkgjIAQgPIAkAhQAKAKAEAGIgQARIgOgQg");
	this.shape_10.setTransform(-112.45,-32.725);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.s6_mc, new cjs.Rectangle(-127.6,-48,196.7,70.2), null);


(lib.s5_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1E2946").s().p("AgZArQgLgGgHgMQgGgLAAgOQAAgNAGgLQAHgMAMgHQALgGANAAQAOAAALAGQAMAHAGAMQAHALAAANQAAANgHAMQgGAMgMAGQgLAHgOAAQgMAAgNgHgAgQgcQgHAFgFAHQgFAHAAAJQAAAKAFAHQAFAIAHAEQAIAEAIAAQAOAAAKgJQAJgKAAgOQAAgIgEgIQgFgHgHgFQgJgFgIAAQgHAAgJAFg");
	this.shape.setTransform(15.375,56.425);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#1E2946").s().p("AglCSIgOgLQAOgQAIgSQAIgTAEgRQAEgQABgVIACgiIAAhYIBNAAQgGgNgHgKQgHgMgLgNIAWgJQAJAKAKAPQAHAKAGAMIgXAKIBPAAIAACBIgYAAIAAgWIhtAAIgBAUQgBARgGAZQgEAUgJAVQgJAUgPAQIgFgGgAANgIIBtAAIAAhAIhtAAgAiCCKIgFgMIAVAAIAMAAQABAAABAAQABAAAAAAQABAAAAgBQAAAAABAAQAAAAAAAAQABgBAAAAQAAgBAAgBQAAgBAAgBIAAhVIgqAMIgHgYQAKgCAWgGIARgFIAAhHIgsAAIAAgYIAsAAIAAhCIAYAAIAABCIAmAAIAAAYIgmAAIAAA/IAlgKIADAXIgoAMIAABdQAAAKgCAGQgCAHgHACQgGADgLABIgbABg");
	this.shape_1.setTransform(-7.875,46.95);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#1E2946").s().p("AAgCYIAAhnIgOAUQgSAXgRAQQgSAQgVANIgLgOIgHgGQAVgLASgPQAWgRANgSQAJgMAIgMIhRAAIAAgWIBgAAIAAgpIhHAAIAAhpICqAAIAABpIhKAAIAAApIBcAAIAAAWIhOAAQAHANAKAMQARAUARAPQASAQASAJIgGAHIgHAGIgEAHQgRgLgTgSQgUgTgOgUIgOgWIAABpgAgQg1IB6AAIAAg9Ih6AAgAhsCXIAAi9IAAABQgSAZgSAQIgCgHIgLgQQAPgPARgWQARgZAMgUQAOgbAIgXIAYAIQgLAbgPAcIgIAOIAADhg");
	this.shape_2.setTransform(-42.15,46.95);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FA0031").s().p("AgXCZQgYAAgLgDQgNgEgFgJQgFgIAAgQIAAgwIAoAAIAAAvQAAAHAEACQAEACAOAAIA3AAQAIAAAFgDQAEgCACgIQACgKAAgPIALAGIAaAHQgCAVgGANQgGANgLAEQgLAEgTAAgAiaCCIAYgoIAIgUIAjAMIgOAgQgIAUgHALgABqB5QgEgKgIgOIgMgWIAjgLIAaAsIAKATIgmANgAAABgIgcgiIAegOIAqAuIghARQgCgFgJgKgAiRAwIgKgGQANgQAFgVQAGgTACgUQACgRAAgTIAAgyICXAAIgBgfIAmAAIAAAfIAdAAIgCgCIgRgOIAXgQIASAMIAQAOIgJAGIAeAAIAAAgIhWAAIABAHQADAeAHAZIAAABQATgZAKgeIAkAJQgQApgaAgIgHAIIAAAAQAKANANAAQAGAAADgJQACgIABgWQAHAGAIAEIAQAGQgCAXgGANQgFANgJAFQgIAFgPAAQgYAAgRgQIgGgHQgMALgOAIIgRgTIgGgFIAAAMIhhAAIAAhMIBhAAIAAA7QAQgJAOgNIgCgFQgJgcgGgnIgCgUIh1AAIgBAzQgCAUgDARQgEARgHARQgGASgLAOgAgzAQIAkAAIAAgXIgkAAgAhTgvIAAgbIBlAAIAAAbg");
	this.shape_3.setTransform(-77.225,46.575);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FA0031").s().p("Ag5CRIgKgJIgKgHQATgOAJgPQAIgOAEgRQACgRAAgMIAAgfIAjAAIgBA8QgCAQgEAOQgFAPgLAOQgJAOgSAMgAiVB+IAqhCQAJgQALgXIAdAbIg5BogABqCWQgHAAgGgCQgFgBgFgFQgEgFgCgGQgBgHgBgRIAAhiIAkAAIAABjIABAGIABADIABACIACAAIAFAAIAFgBQACgCAAgGIABggQAEADAJAFIAOAGQAAAMgCALQAAAKgCAGQgEAKgHAFIgIADIgKABgAAUCOIAAiFIAjAAIAACFgABrgNIiQAMIgJACIgDgKIgGgZIAMgEQAJgDAEgEIAcghIg5AAIAAgjIBWAAIgCgHIgJgZIAkgIIALAYIAEAQIBPAAIAAAjIgtAAIAQATIAUAZQAJAMAGAKIggAUIgNgVgAAMgoIBIgEIgRgUIAXgOIgxAAgAhugFQgMgIgLgFQgKgGgMgEIAVgeIAWAJIAXAMQALAGAHAGIgXAgQgGgHgKgFgAhiheIgWgOIgVgMIAVgdQAKAEAMAHIAWAMQALAHAGAGIgXAgQgIgIgIgFg");
	this.shape_4.setTransform(-112.3,46.775);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#1E2946").s().p("AhHCWIAAiSQgHARgJASQgKATgLARQgKAQgMAMQgCgEgEgHIgIgMQAKgJAMgQQAKgOAKgSIARgiIAIgUIg7AAIAAgXIBBAAIAAg3IgHABQgVAEgaACIgHgTIBZgRQAUgEAQgHIAPATQgQAHgXAFIgPAEIAAA8IA5AAIAAAXIg5AAIAAAIIA2BAIgOAUIgog4IAACRgAAWCIIAAkBIB7AAIAAD+IgZAAIAAgYIhKAAIAAAbgAAuBVIBKAAIAAi2IhKAAg");
	this.shape_5.setTransform(94.425,7.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FA0031").s().p("ABNCKIgIgRIAgABQABAAAAgBQABAAABAAQAAAAABAAQAAAAAAAAQABgBAAAAQAAgBAAAAQABgBAAAAQAAgBAAgBIAAgeIAAg8IgvAAIgCAJIgBAEIAkAgIAOAPIgZAWIgggiIgDgEQgGALgJAKQgKANgSAKQgDgFgHgJIgKgLIAABDIgkAAIAAijIBMAAIAAgXIhOAAIAAgiIDNAAIAAAiIhaAAIAAAXIBTAAIAAB8QAAAMgDAIQgDAJgIAEQgIADgNACIgbABQgBgGgEgMgAgQBWQANgHAHgJQAJgJAEgLQAFgNABgJIAAgCIgnAAgAh8CRIgLgKQgFgFgEgBQAPgQAJgSQAJgVAEgRIABgGIgkAVIgMglIAcgMIAZgMIABgoIgcAQIgFgTIgSgsIAcgPQAKARAGAPIAHAVIAAhQIBvAAIAAgDIgHgaIArgIIAMAlIBgAAIAAAkIjZAAIAAA/IgCArQgBATgHAbQgGAZgKAVQgKAVgSASg");
	this.shape_6.setTransform(60.825,7.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FA0031").s().p("AiJCKIgUgSQASgOAIgPQAIgOADgRQACgSAAgLIAAgNIgfAAIAAgkICZAAIAAAkIgYAAIAABMQAAAHACACQADADAGACIAUABIBTAAQALAAAGgDQAFgDADgJQADgNABgPQAGAEALAEIASAFQgDAagGANQgFAOgOAGQgMAFgXAAIhWAAQgZAAgPgEQgOgFgGgKQgGgKAAgUIAAhMIgYAAIAAANQAAAVgEASQgEAWgLATQgKAVgUAPgAA1BeIgFgRIgHgRIAgAAQABAAAAAAQABAAAAAAQABAAAAgBQABAAAAAAIABgEIAAhNIhLAAIAAgjIBLAAIAAggIAYAAIAAgVIjMAAIAAAbIBfAAIAAAkIh2AAIAAgjIgQAAIAAhAIEcAAIAABAIgbAAIAAAZIAiAAIAAAjIgiAAIAABOQAAANgDAHQgDAIgJAEQgHAEgOABIgTABIgIAAgAAcAiIgTgiIAegNQAIAJAIAPQAIAOADALIggAPIgGgRg");
	this.shape_7.setTransform(26.175,7.975);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#1E2946").s().p("AAmCNIgFgMIAoAAQAFAAAAgCQAAAAABAAQAAAAAAgBQAAAAAAgBQAAgBAAAAIAAg/IiEAAIAAgWICEAAIAAgdIh9AAIAAgTIDCAAIAAATIgsAAIAAAdIAxAAIAAAWIgxAAIAAA/QAAAJgCAGQgEAGgGACQgHADgNABIgfABgAhlCXIAAiXIgGAFQgQARgQANIgOgYQAPgLAQgOQAMgMAQgSQANgSAKgQIAWAJQgMAVgOASIgBABIAAC0gAAFBuIgOgRIgPgPIASgMQAIAIAOAPQAOAQAEAHIgTAOQgDgHgHgJgAgZggIAAhtICdAAIAABtgAgBgzIBsAAIAAgbIhsAAgAgBhgIBsAAIAAgaIhsAAgAiThSQAPgLALgKQAOgLALgMQALgLAIgOIAXAJQgJAPgNAOQgNAOgQAOQgLAKgSANg");
	this.shape_8.setTransform(-8.75,7.35);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#1E2946").s().p("AgxCIQAdgRARgVQAQgUAJgWQAJgWADgTIABgDIhLAAIAAgWIBMAAIABgMIAAgxIAWAAIAAAxIAAAMIBYAAIAAAWIhVAAQAKAmAUAeQAVAiAmARIgGAGIgKAOQgZgNgTgVQgSgUgOgeIgIgVIgGAUQgJAWgTAXQgRAWgfATgAh6CKQgDgHgCgEQAXADALgDQAEAAACgBIAFgEQAFgHACgRQADgTAAgXIAAgNIgHAHQgQAOgMAKQgOAKgOAIIgHgKIgIgIQANgGAPgKQAPgKAMgLQALgKAIgMIgBgCQgDgOgHgNIgKAGQgVALgQAIIgQgQQAUgHAQgLIAPgJQgNgPgUgOIAQgNQAWAOANAPIAAAAQARgOAIgKIAVAMQgPAPgNALIgFADIAIARQAGAPADASQACAPAAAUQAAAegDATQgDAVgLAMQgGAIgLABIglACIgCgMgABfgkQgOgNgLgIIAQgMQAIAFAKAIIAQAOQAIAHAFAHIgSANQgGgJgOgMgAhAhLIAAgbIhOAAIAAgXIBOAAIAAgaIAYAAIAAAaIBVAAIAAgaIAZAAIAAAaIBNAAIAAAXIhNAAIAAAZIgZAAIAAgZIhVAAIAAAbg");
	this.shape_9.setTransform(-43.45,7.325);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#1E2946").s().p("AAzCWIgCgMQgDgGgDgGIAcACIATAAIAIgBQADAAADgEQADgFADgMQADgLADgbIAGiGIhhAAIgGAMQgJASgLASIgVgOQALgNAKgUQAKgVAHgUQAHgXAFgVIAYAFQgGAZgJAXIgDAIIBwAAIAAAMQgBBAgCAdIgEA/QgDAcgDALQgDAOgFAFQgFAGgGAEQgGADgJAAIgVABIgbgBgAiQBtIB+gXIABAWIh7AZgAiLAyIgEgHQAHgCAFgFIAcgdQAKgMAIgLIAEgGIgyAHIgGACIgIgXQAFgBAEgGIALgNIAIgOIAphPIAXAKIgUApQgKARgOAWIgOAUIAtgFIADgDIATghIAWAMQgWAigZAgQgPATgQARIBOgMIABAVIhqATIgIADgAA1AnIgWgaIgZgXIARgOQALAKAOANIAXAYQAKALAIAMIgTAPQgGgJgLgNg");
	this.shape_10.setTransform(-78.25,7.225);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#1E2946").s().p("AB2B/IgsgmIARgPIA9A1IgRARIgRgRgAiHCFQgDgJgCgDIAlAAIAFgCQAAAAAAAAQABgBAAAAQAAgBAAAAQAAgBAAgBIAAiAIg2AAIAAgXIBQAAIgKgHQgNgLgOgJIgbgSIAOgQIAdATQAHgGAKgKIARgXIADgDIhaAAIAAgWIBqAAIAEgCIAQALQgIANgKANQgJAMgMANIgRAQIAeAVIgHAJIAXAAIAEgBIAPAEIgOAnQgIAYgFAJIgTgFIASgvIgjAAIAACBQAAAJgCAHQgEAFgGADQgHACgLABIgdABgAgUCGQgEgGgEgDQAdgLAQgLQASgNAIgOQAJgOABgOQADgOAAgNIAAhBIAYAAIAABCQAAAPgDAQQgDAQgKARQgIAQgUAPQgVAQgcAKgAAABFIAAidIAyAAIAJghIhFAAIAAgXICiAAIAAAXIhCAAIgMAhIBBAAIAACcIgYAAIAAiFIhbAAIAACGg");
	this.shape_11.setTransform(-112.45,8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#1E2946").s().p("AhHCSIgHgHIgIgFQAfgPAUgSQAUgRALgSQAMgSAFgSQAGgRABgRIACgyIAaAAIAAAUIAAAXQAGAdALAZQAPAfAUAUQAVAXAfAKIgGAHIgLAPQgggNgVgZQgWgWgOgjIgHgRIgBACQgHAVgLATQgNAUgVATQgWATgfAQgAiWBlIBEhlIATARIgVAiIgWAjIgWAggABWgHIALgZQAGgPAFgOIADgKIh5AAIgNAdQgLAZgLAQIgQgKIgIgEQAMgPALgXQAMgbAGgUQAJgbAEgZIAaAGQgFAXgIAcIB5AAIAFgCIASAKIgiBZgAh6hhQgKgHgOgGIAPgSIAYANQAMAHALAJIASAOIgQAUg");
	this.shape_12.setTransform(89.2,-32.25);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#1E2946").s().p("AiWANIAAgZIEtAAIAAAZg");
	this.shape_13.setTransform(57.075,-32.65);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#1E2946").s().p("AhhCXIAAiCQgRASgVAQIgEgIIgJgPQAYgQARgUQARgSAQgbIAOgaIhQAAIAAgYIBbAAQAJgVAJgeIAZAGQgGAWgKAXICqAAIAAAYIi0AAIgCAGQgRAhgVAdIAACegAgzCRIAAgXIBXAAIAAheIhJAAIAAgXIBJAAIAAg/IAZAAIAAA/IBLAAIAAAXIhLAAIAABeIBXAAIAAAXg");
	this.shape_14.setTransform(22.7,-32.375);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#1E2946").s().p("AAqCLIgFgNIAuAAIALAAQAGAAACgCQACgBgBgGIAAjUIibAAIAAgYIDNAAIAAAYIgZAAIAADVQAAAMgDAIQgEAGgJADQgIACgSABIgoABIgEgMgAhrCXIAAi6QgPAWgQARIgJgQIgFgIQAQgRANgUQAOgUANgZQAMgaAIgWIAXAGQgKAdgNAaIgHANIAADjgAgqBYIAAiIIBmAAIAABxIhPAAIAAAXgAgTArIA5AAIAAhGIg5AAg");
	this.shape_15.setTransform(-11.6,-32.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#1E2946").s().p("AiHCNIgJgKQAigMAZgcQAIgIAGgKIg5gsIAMgmIALgvIABgEIgoAAIAAgXIAtAAIAEgWQAFgaACgUIAZACIgIAwIgEASIA1AAIAFgBIAQADQgEAzgKAlQgIAhgPAcIAPANQAOANAIAJIgRAVQgIgLgNgMIgNgMQgMASgPANQgVAUgcAMgAhkAUIAqAgQAHgOAGgPQAMgjAGgwIg1AAgAAPCPIAAkCICCAAIAAD9IgZAAIAAgUIhRAAIAAAZgAAnBfIBRAAIAAi7IhRAAg");
	this.shape_16.setTransform(-46.525,-32.275);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#1E2946").s().p("AiKCUIgNgHQALgSAFgVQAFgUACgWIABhlIgHAJIgFgEIgNgKQARgSAOgdQANgcAIgfIAWAGIgHAYIAtAAIAEgBIAPAJIgJAWQgEAMgGAJIgCADIAiAAIAADAQAAAHgBAFQgDAGgEACQgGADgIAAIgUABIgDgLQgBgEgDgGIAPAAIAJAAQAFAAAAgEIAAgyIgeAAIAAA9IgSAAIAAg9IggAAIgCAPQgEATgFAPQgEAOgKARgAg6A2IAeAAIAAgtIgeAAgAhqATIgBAhIAAACIAfAAIAAgtIgeAAgAg6gIIAeAAIAAgpIgeAAgAhqgIIAeAAIAAgpIgeAAgAhthEIAsAAIAGgMIAIgTIABgDIgrAAQgJAWgHAMgABICXIAAg/IhDAAIAAgXIBDAAIAAgnIgkAAQgIARgKAOIgMgHIgGgDQAJgNAJgVQAIgTADgUIAVAEQgCANgFANIAdAAIAAgeIAXAAIAAAeIAyAAIAAAWIgyAAIAAAnIA6AAIAAAXIg6AAIAAA/gAAFghIgHgIQATgIALgNQALgOAFgQIAFgWIgsAAIAAgUICLAAIAAAJIgDAtQgCAPgCALQgCAJgEAEQgEAEgDACQgDABgIABIgOAAIgUAAIgCgKQgBgHgDgDIAeAAIAGAAQAAAAABAAQAAAAABgBQAAAAAAAAQABgBAAAAQADgDABgIIAFgwIgxAAIgGAcQgHAUgNAQQgNAQgWAKg");
	this.shape_17.setTransform(-80.475,-32.25);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#1E2946").s().p("AhJB/IgGgNIAwABIAMAAQAGAAACgCQACgBAAgFIAAibQAPgIAPgKQAOgJAQgMIAcgXIADgDIjUAAIAAgYIDsAAIAGgCIATAPQgOAPgWATQgVASgXAPQgTANgQAJIAACPQAAALgEAHQgEAGgJAEQgKACgQABIgqABQgBgFgDgIg");
	this.shape_18.setTransform(-112.575,-31.075);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.s5_mc, new cjs.Rectangle(-127.9,-47.5,236.8,109.7), null);


(lib.s4_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1E2946").s().p("AjODHQgGgOgHgKQBQgDA/gNIAVgEQg0gOg4gLIAjgrIAJgMIhsAAIAAg0ICOAAIAQgbIh/AAIAAiNIBtAAIAAgcIiEAAIAAg0IG0AAIAAA0IiHAAIAAAcIB3AAIAACNIjmAAIAaAFIgMAWIDzAAIAAA0IhfAAQgSAigYAYIgEAFIA7ARIBGAWIgwAvQgmgPg0gQIgygPIgHADQgnASg4ALQg4ALhDAFQgCgJgHgSgAg+BdIgFAHIAmAIIAyANIACgBQAZgSATgbIhzAAIgOASgABSgzIA8AAIAAgvIg8AAgAgfgzIA4AAIAAgvIg4AAgAiMgzIA1AAIAAgvIg1AAgAgfiRIA4AAIAAgcIg4AAg");
	this.shape.setTransform(104.825,35.675);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#1E2946").s().p("AjjDjIAAgvIDDAAIAAgaIieAAIAAguICeAAIAAgVIiNAAIAAifICNAAIAAgTIjAAAIAAgvIDAAAIAAgWIg0ACIhaADQgBgKgEgOIgHgXQAqAAAvgDIBbgFQA2gDAegEQAtgFAbgEIAcAuQglAGgrAEQgaADgtADIAAAaIDFAAIAAAvIjFAAIAAATICVAAIAACfIiVAAIAAAVICoAAIAAAuIioAAIAAAaIDJAAIAAAvgAAbAvIBYAAIAAgWIhYAAgAhzAvIBTAAIAAgWIhTAAgAAbgKIBYAAIAAgXIhYAAgAhzgKIBTAAIAAgXIhTAAg");
	this.shape_1.setTransform(52.925,34.05);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#1E2946").s().p("AAsDpIAAmtQgXA5gdAxIAkAAIAAA0IhKAAIgKANIgWAYIBZAAIAADiIg4AAIAAgTIhRAAIAAAaIg3AAIAAiYIgZAOIgWgiIgMgQQBDgfA1gzIhrAAIAAg0IBXAAIAAgpIhBAAIAAg0IBBAAIAAgxIA4AAIAAAxIAzAAIAAAbQAOgcALgdIA0AOIAAgJICRAAIAJgCIArAbIgdBMQgPAmgQAjQAUAVAMAVQAMAVADATQAEARAAARQAAAdgHASQgHATgOAKQgOAKgWADIgrABQgBgNgEgQQgDgQgIgNIASABIAOAAQAGAAAFgCQAHgBADgCQAHgEADgJQACgJAAgMQAAgUgKgbQgMgbgegcIAsh9Ig/AAIAAGAgAh+CeIBRAAIAAgjIhRAAgAh+BOIBRAAIAAggIhRAAgAhUhaIAKAAQAOgTANgWIglAAg");
	this.shape_2.setTransform(0.375,34.925);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#1E2946").s().p("AjYDpIAAlcIA+AAIAAFcgAB1DLQgGgQgFgKIAoAAQAFAAACgCQACgBAAgGIAAlCIjtAAIAAg4IErAAIAAF7QAAAVgFAMQgEAMgNAGQgNAHgRACQgSABgYAAgAhnCQIAAjvIDNAAIAADvgAgxBgIBfAAIAAgwIhfAAgAgxAAIBfAAIAAgvIhfAAgAikiUIgVgcQgLgOgNgNIAwgdIAYAZIAWAaQAMAQAEAJIgzAgQgHgOgHgKg");
	this.shape_3.setTransform(-51.825,34.875);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#1E2946").s().p("AAlDlQgCgNgGgRQgFgQgIgOIBTABQAJAAADgDQADgDAAgHIAAjtIiUAAIAAg7ICUAAIAAhZIA9AAIAABZIAzAAIAAA7IgzAAIAADtQAAAcgGANQgHAOgRAHQgRAHgaACQgUABgYAAIgVAAgAjhC5IAAl5ICsAAIAAFQIh0AAIAAApgAipBbIA8AAIAAhbIg8AAgAipg0IA8AAIAAhXIg8AAgAAWA7IgzhQIAxgaIBLBtIg2AfQgFgMgOgWg");
	this.shape_4.setTransform(-103.175,34.5393);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#1E2946").s().p("Ah7DoIAAixIgHARQgOAggPAZQgPAZgSATQgFgMgJgQIgRgcQAQgQAPgWQAPgXAMgXQAMgYAKgZIAGgPIhLAAIAAg4IBZAAIAAhAIAAAAQgqAHgdADQgCgLgEgNIgKgXQAlgFAdgGQAegFAigKQAcgHAagKIAmAvQgaAKgmAIIgLADIAABMIBJAAIAAA4IhJAAIAAAIIBNBWIgiAyIgrhCIAAC5gAAXDRIAAmOIDJAAIAAGKIg+AAIAAgkIhRAAIAAAogABRBvIBRAAIAAjyIhRAAg");
	this.shape_5.setTransform(105.05,-25.075);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#1E2946").s().p("Ag5DVQgGgPgEgJIA/ABQAGgBACgCQADgCAAgGIAAghIiDA9IgXgxIAvgRIArgQIgRgMIgyghIAagcIgNAAIAAgpIB2AAIAAgWIiFAAIAAgqICFAAIAAgVIhwAAIAAgpIBwAAIAAgaIiOAAIAABeQAAAjgCAfQgCAlgGAnQgFAlgKAmQgMAlgQAcIghgYIgQgJQAQgaAJggQAKghADghQAFgkAAgeIACjNIC+AAIgPgeIA7gOIASAfIAGANICkAAIAAA0IiiAAIAAAaIB8AAIAAA4IAsAAIAAAzIgsAAIAAA8IgUAAIAqAjQgYAPgZAOIgaAPIAZANQAgAQApAJQgJAIgJAOIgRAZQgrgMgggWQghgTgageIAAAvQAAAWgGALQgGALgPAGQgOAFgYACIg0ABQgCgKgGgPgAgVBcIgaAdIA2gVIAAgwIhcAAgABEA6QAOAYATATIANgJIAfgVIAYgTIhlAAgABEALIBDAAIAAgWIhDAAgABEg1IBDAAIAAgVIhDAAg");
	this.shape_6.setTransform(53.7,-25.45);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#1E2946").s().p("Ah8DQIgLgIIAAAiIg0AAIAAj7QgLARgMAQIgGgTIgVgtQAagjAUgxQAXg1ALgwIA2APQgLAogRAtIgEAKIAAE/QAggXAWgmIgBgBQgXgkgQg8IAqgNQAIAgAMAZQANgoAGg0IgsAAIgMAHQgFAEgBAEIgOgcIgJgNQAHgCAKgKQAKgKAGgLQAGgHAJgVQAIgOANghIADgIIg2AAIAAgyIBJAAIAQgHIAgAXQgQAugVArIgVApIASAAIAJgBIAdAHQgJBtgaBGIgBABQALALANAHQAZAQAfAFQAcAGAmAAIB0gBQgGALgFAOIgIAaIhkAAQguAAgigHQglgHgegUQgKgGgJgIQgWAkgdAVgABOCkIAAguIhDAAIAAguIBDAAIAAgYIg5AAIAAgtIA5AAIAAgXIg2AAIAAgpIA2AAIAAgbIhKAAIAAgrIBKAAIAAgYIg2AAIAAgqIA2AAIAAghIAyAAIAAAhIBPAAIAABCIAeAAIAAArIgeAAIAABEIhPAAIAAAXIBRAAIAAAtIhRAAIAAAYIBeAAIAAAuIheAAIAAAugACAg9IAiAAIAAgbIgiAAgACAiDIAiAAIAAgYIgiAAg");
	this.shape_7.setTransform(0.7,-25.225);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#1E2946").s().p("AA5DoQAAgNgGgQQgFgRgIgNQAaADATAAIAeABQAIAAAEgCQAEgBAFgGQAHgFAEgVQAEgSADgoQAEgrACgxIADhbIhqAAIgMAXQgQAggRAYIgggZIgGgEIAADqIiGAAIAAAlIg3AAIAAl1IA5AAIAFgTIAGggQADgTABgLIBBAJIgRAzIgJAVIBOAAIAABSQALgQAKgUQANgaANgjQAMggAHgiIA6AOQgHAdgMAjICNAAIgBAbQgBBVgDA5QgEBAgDAhQgEAmgFAWQgEAVgJAKQgJAPgMAFQgLAGgQACQgMACgXAAgAiiCFIBQAAIAAhjIhQAAgAiigRIBQAAIAAhRIhQAAgABBBGIgzhQIAvgaIAaAkIAbAoQAOAVAGANIgzAgQgIgSgKgSg");
	this.shape_8.setTransform(-51.225,-25.45);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#1E2946").s().p("AAEDLQgHgVgFgIIAwAAQAFAAACgBQACgCAAgFIAAkAIg5AAIgJATQgUAjgTAXIgwgnQAUgWAQgdQAQgfAMgfQANggAJgkIA5ANQgKAngOAkICuAAIAJgCIAqAIIgKA/IgMA2IgzgJIAIg7IhCAAIAAEBQgBAVgEANQgFAOgOAHQgMAHgSADQgQACgcAAQgBgMgGgTgAiuDpIAAkAQgQAXgRAQIgIgSIgZgrQAVgVAYggQATgdAUgkQARghAOglIA4ASQgPAngXAuIgJASIAAFZgAg6CdIgkgVQAWgaAPgpQARgoAHgoIA6ALQgHAegKAhQgLAggMAaQgNAcgOATQgIgGgIgFgACnBzQgHgcgLgeQgKgfgMgZIA1gRQANAXALAfQAKAZAKAhQAHAZAEAZIg6AUQgCgTgIggg");
	this.shape_9.setTransform(-104.6,-25.125);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.s4_mc, new cjs.Rectangle(-128.6,-49.2,256.3,107.5), null);


(lib.logo = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E41837").s().p("AgEAJQgDgBgBgDIgCgFIACgEIAEgEIAEgCQADABACABIAEAEIACAEIgCAFQgBADgDABQgCACgDAAIgEgCgAgEgGQAAAAgBAAQAAAAAAABQgBAAAAABQAAAAAAABIgCADIACAFQAAAAAAABQAAAAABAAQAAABABAAQAAAAAAAAIAEACQABAAAAAAQABAAAAAAQABgBAAAAQABAAAAgBQABAAABAAQAAAAAAgBQABAAAAAAQAAgBAAAAQABgBAAgBQAAAAABgBQAAAAAAgBQAAAAAAgBIgCgDQAAgBAAAAQAAgBgBAAQAAgBAAAAQgBAAgBAAIgEgCIgEACgAADAGIgBgCIgCgCIgBgBIgBAAIAAAFIgCAAIAAgKIAEAAIACAAIABABIABABIgBACIgCABIABABIADAEgAgCAAIACAAIACAAIAAgBIAAgBIgBgBIgBAAIgCAAg");
	this.shape.setTransform(55.35,-6.45);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E41837").s().p("AgwAxQgUgVAAgcQAAgbAUgVQAVgVAbAAQAQAAANAHQANAHALAOIAAgYIAQAAIAACDIgQAAIAAgWQgMANgNAGQgMAHgQAAQgbAAgVgVgAgZgtQgLAHgIAMQgGANgBANQABAOAGANQAIANAMAHQAMAHANAAQAOAAAMgHQANgHAGgMQAIgNgBgOQAAgWgPgQQgPgPgWAAQgNAAgNAHg");
	this.shape_1.setTransform(46.3,-0.925);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#E41837").s().p("AApBEIAAg/QAAgXgCgHQgDgNgJgGQgIgHgNAAQgPAAgMAKQgNALgDAOQgDAMAAAXIAAAxIgRAAIAAiDIARAAIAAAXQAKgNANgHQANgHANAAQAPAAALAHQAMAJAFAMQAGANAAAaIAABEg");
	this.shape_2.setTransform(30.575,-1.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#E41837").s().p("AghBEIAAiDIASAAIAAATQAJgMAHgFQAIgGAKAAQAHAAAHAFIgIAOQgGgCgDgBQgJAAgHAIQgIAHgEAOQgDALAAAiIAAAtg");
	this.shape_3.setTransform(19.45,-1.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#E41837").s().p("AgxAwQgTgUAAgcQAAgXAQgVQAUgZAgAAQAiAAAUAaQANASABAaIh2AAQABAXAOAPQAOAPAVAAQAIAAALgDQAKgEAGgGQAIgHAGgMIAPAIQgGAOgKAIQgJAIgMAFQgMAFgOAAQggAAgSgWgAgggoQgLAJgFATIBhAAQgCgOgIgIQgEgHgNgGQgKgFgMAAQgTAAgNAMg");
	this.shape_4.setTransform(6.75,-0.925);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#E41837").s().p("AgwBJQgUgUAAgeQAAgcAUgTQAVgVAbAAQAPAAAOAHQANAGAKAPIAAhMIARAAIAAC3IgRAAIAAgWQgKAMgOAHQgNAGgPABQgcAAgUgVgAgZgVQgMAHgHAMQgHAMAAAOQAAAPAHAMQAHAMAMAHQANAIAMAAQAPAAAMgIQANgGAGgNQAIgMgBgPQAAgVgPgQQgOgQgXAAQgNAAgNAIg");
	this.shape_5.setTransform(-10.2,-3.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#E41837").s().p("AgxAxQgTgVAAgcQAAgaASgUQAUgXAeAAQAfAAAUAXQASAUAAAaQAAAcgTAVQgTAVgfAAQgeAAgTgVgAgjgkQgQAQAAAVQAAAOAHANQAIANALAGQANAHAMAAQAOAAAMgHQALgGAIgNQAHgNAAgOQAAgVgQgQQgOgQgWAAQgVAAgOAQg");
	this.shape_6.setTransform(-26.6,-0.925);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#E41837").s().p("ABSBEIAAhIQAAgUgEgJQgCgHgIgFQgIgGgKAAQgMABgKAHQgLAHgEAMQgFAOAAAaIAAA0IgQAAIAAhEQAAgWgDgKQgDgHgIgGQgHgFgKgBQgLABgLAHQgKAHgGAMQgEAMAAAYIAAA4IgRAAIAAiDIARAAIAAAWQAIgLAKgHQAMgIAQAAQAIAAAKAEQAIADAFAHQAFAGAEAMQAJgQANgIQANgIAOAAQANAAALAHQALAHAFAMQAFAOAAAXIAABIg");
	this.shape_7.setTransform(-46.35,-1.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#BFE6F6").s().p("AgeAHQgGAAAAgHQAAgGAGAAIA9AAQAGAAAAAGQAAAHgGAAg");
	this.shape_8.setTransform(-52.675,12.025);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#B2E1F5").s().p("AgeAHQgGAAAAgHQAAgGAGAAIA9AAQAGAAAAAGQAAAHgGAAg");
	this.shape_9.setTransform(-43.45,12.025);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#A4DCF3").s().p("AgeAHQgGAAAAgHQAAgGAGAAIA9AAQAGAAAAAGQAAAHgGAAg");
	this.shape_10.setTransform(-34.225,12.025);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#97D7F1").s().p("AgeAHQgGAAAAgHQAAgGAGAAIA9AAQAGAAAAAGQAAAHgGAAg");
	this.shape_11.setTransform(-24.725,12.025);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#8BD2F0").s().p("AgeAHQgGAAAAgHQAAgGAGAAIA9AAQAGAAAAAGQAAAHgGAAg");
	this.shape_12.setTransform(-15.5,12.025);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#7ECDEE").s().p("AgeAHQgGAAAAgHQAAgGAGAAIA9AAQAGAAAAAGQAAAHgGAAg");
	this.shape_13.setTransform(-6.275,12.025);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#71C9EC").s().p("AgeAHQgGAAAAgHQAAgGAGAAIA9AAQAGAAAAAGQAAAHgGAAg");
	this.shape_14.setTransform(3.225,12.025);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#64C4EB").s().p("AgeAHQgGAAAAgHQAAgGAGAAIA9AAQAGAAAAAGQAAAHgGAAg");
	this.shape_15.setTransform(12.45,12.025);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#56BFE9").s().p("AgeAHQgGAAAAgHQAAgGAGAAIA9AAQAGAAAAAGQAAAHgGAAg");
	this.shape_16.setTransform(21.675,12.025);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#4ABAE7").s().p("AgeAHQgGAAAAgHQAAgGAGAAIA9AAQAGAAAAAGQAAAHgGAAg");
	this.shape_17.setTransform(31.175,12.025);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#3CB5E5").s().p("AgeAHQgGAAAAgHQAAgGAGAAIA9AAQAGAAAAAGQAAAHgGAAg");
	this.shape_18.setTransform(40.4,12.025);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#26ADE2").s().p("AgeAHQgGAAAAgHQAAgGAGAAIA9AAQAGAAAAAGQAAAHgGAAg");
	this.shape_19.setTransform(49.625,12.025);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.logo, new cjs.Rectangle(-56.3,-12.6,112.69999999999999,25.299999999999997), null);


(lib.kv_inner_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.kv();
	this.instance.setTransform(-320,-480);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.kv_inner_mc, new cjs.Rectangle(-320,-480,640,960), null);


(lib.code_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("AAkDvQgEgEAAgFIAFAAQAAADADADQACADAFAAQAEAAACgDQADgDAAgEQAAgFgCgCQgDgDgEAAQgIAAgCAGIgFAAIACgYIAZAAIAAAEIgVAAIgBAOQAEgEAHAAQAGAAAEAEQADADAAAHQAAAGgEAEQgEAEgGAAQgHAAgEgEgAggDuQgEgGAAgJIAAgCQAAgJAEgGQAFgGAHAAQAHAAAEAGQAFAGAAAJIAAACQAAAJgFAGQgEAFgHAAQgHAAgFgFgAgcDRQgDAFAAAHIAAACQAAAHADAEQADAFAFAAQAFAAADgFQADgEAAgHIAAgCQAAgHgDgFQgDgEgFAAQgFAAgDAEgAiEDvQgEgEAAgHQAAgIAEgEQAEgEAHAAQAGAAADADQAEADAAAFIgFAAQgBgHgHAAQgEAAgDADQgDAEAAAFQAAAFADADQACADAFAAQADAAACgCQADgCAAgDIAFAAQAAAFgEADQgEADgFAAQgHAAgEgEgAivDtQgGgGAAgJQAAgKAGgGQAFgGAJAAQAJAAAGAGQAFAGAAAKQAAAJgFAGQgGAGgJAAQgJAAgFgGgAirDSQgEAEAAAIQAAAHAEAFQAEAEAGAAQAHAAAEgEQAEgFAAgHQAAgIgEgEQgEgFgHAAQgGAAgEAFgAkCDwQgEgEAAgGIAFAAQAAAEADACQADADAEAAQAEAAADgDQADgCAAgDQAAgEgDgCQgCgBgFAAIgEAAIAAgFIADAAQAFAAACgCQADgCAAgDQAAgDgDgCQgCgCgEAAQgEAAgDACQgCACAAAEIgFAAQAAgGAEgDQAEgEAGAAQAGAAAEADQAEAEAAAEQAAAIgHACIAGADQACADAAAEQAAAFgEAEQgEADgHAAQgHAAgEgDgAlGDuQgEgGAAgJIAAgCQAAgJAEgGQAFgGAHAAQAHAAAEAGQAFAGAAAJIAAACQAAAJgFAGQgEAFgHAAQgHAAgFgFgAlCDRQgDAFAAAHIAAACQAAAHADAEQADAFAFAAQAFAAADgFQADgEAAgHIAAgCQAAgHgDgFQgDgEgFAAQgFAAgDAEgAlrDuQgEgGAAgJIAAgCQAAgJAEgGQAFgGAHAAQAHAAAEAGQAFAGAAAJIAAACQAAAJgFAGQgEAFgHAAQgHAAgFgFgAlnDRQgDAFAAAHIAAACQAAAHADAEQADAFAFAAQAFAAADgFQADgEAAgHIAAgCQAAgHgDgFQgDgEgFAAQgFAAgDAEgAmQDuQgEgGAAgJIAAgCQAAgJAEgGQAFgGAHAAQAHAAAEAGQAFAGAAAJIAAACQAAAJgFAGQgEAFgHAAQgHAAgFgFgAmMDRQgDAFAAAHIAAACQAAAHADAEQADAFAFAAQAFAAADgFQADgEAAgHIAAgCQAAgHgDgFQgDgEgFAAQgFAAgDAEgAmyDvQgEgEAAgFIAFAAQAAADADADQACADAFAAQAEAAACgDQADgDAAgEQAAgFgCgCQgDgDgEAAQgIAAgCAGIgFAAIACgYIAZAAIAAAEIgVAAIgBAOQAEgEAHAAQAGAAAEAEQADADAAAHQAAAGgEAEQgEAEgGAAQgHAAgEgEgAo9DtQgGgGAAgJQAAgKAGgGQAFgGAJAAQAJAAAGAGQAFAGAAAKQAAAJgFAGQgGAGgJAAQgJAAgFgGgAo5DSQgEAEAAAIQAAAHAEAFQAEAEAGAAQAHAAAEgEQAEgFAAgHQAAgIgEgEQgEgFgHAAQgGAAgEAFgApnDtQgGgGAAgJQAAgKAGgGQAFgGAJAAQAHAAAFAEQAFAEABAGIgGAAQgBgEgDgCQgDgDgFAAQgGAAgEAFQgEAEAAAIQAAAHADAFQAEAEAHAAQAFAAADgCQADgDABgEIAGAAQgBAHgFADQgFAEgHAAQgJAAgFgGgAsUDtQgFgGAAgJQAAgKAFgGQAGgGAJAAQAHAAAFAEQAFAEABAGIgGAAQgBgEgDgCQgEgDgEAAQgHAAgEAFQgEAEAAAIQAAAHAEAFQAEAEAHAAQAFAAAEgDQAEgDAAgGIAAgBIgNAAIAAgFIASAAIAAAXIgFAAIAAgGIgFAEQgEACgEAAQgJAAgGgGgAs5DvQgEgEAAgGIAFAAQAAAEADADQADACAFAAQAFAAACgBQADgCAAgEQAAgDgDgCIgJgCQgGgBgDgCQgEgDAAgGQAAgFAEgDQAEgEAGAAQAHAAAEAEQAEADABAGIgGAAQAAgEgDgCQgDgCgEAAQgEAAgDACQgCACAAADQAAADADACIAIACQAHABADACQAEADAAAGQAAAFgEAEQgEADgHAAQgHAAgFgEgAAADzIAAgEIAPgPIAFgFQACgDAAgDQAAgEgCgCQgDgCgEAAQgEAAgDACQgCADAAAEIAAABIgEAAIAAgBQAAgGADgEQAEgEAGAAQAHAAADAEQAEADAAAGQAAAEgCAEIgHAGIgMALIAVAAIAAAFgAhFDzIAAgEIAQgPIAFgFQACgDAAgDQAAgEgCgCQgDgCgEAAQgEAAgDACQgCADAAAEIAAABIgFAAIAAgBQAAgGAEgEQAEgEAGAAQAHAAADAEQAEADAAAGQAAAEgCAEIgHAGIgMALIAVAAIAAAFgAhcDzQgEAAgCgCQgCgCAAgEIAAgSIgGAAIAAgFIAGAAIAAgIIAFAAIAAAIIAIAAIAAAFIgIAAIAAASIABACIACABIAFAAIAAAFgAjSDzIAAgsIAFAAIAAAsgAkmDzIAAgEIAQgPIAFgFQACgDAAgDQAAgEgCgCQgDgCgEAAQgEAAgDACQgCADAAAEIAAABIgFAAIAAgBQAAgGAEgEQAEgEAGAAQAHAAADAEQAEADAAAGQAAAEgCAEIgHAGIgMALIAVAAIAAAFgAnXDzIAAgEIAQgPIAFgFQACgDAAgDQAAgEgCgCQgDgCgEAAQgEAAgDACQgCADAAAEIAAABIgFAAIAAgBQAAgGAEgEQAEgEAGAAQAHAAADAEQAEADAAAGQAAAEgCAEIgHAGIgMALIAVAAIAAAFgAoJDzIgPgqIAGAAIANAkIAMgkIAGAAIgPAqgAqpDzIAAgqIAQAAQAHAAAEADQADAEAAAGQAAAGgDADQgEAEgHAAIgKAAIAAAQgAqjDeIAKAAQAEAAADgCQACgDAAgDQAAgEgCgCQgDgCgEAAIgKAAgAq2DzIgWghIAAAhIgFAAIAAgqIAFAAIAWAgIAAggIAFAAIAAAqgAnwDkIAAgEIAUAAIAAAEgAqGDkIAAgEIAUAAIAAAEgArsDkIAAgEIAUAAIAAAEgAEeCiQgEgCgBgFIAFAAQACAGAIAAQAKAAAAgKIAAgEQgEAGgHAAQgGAAgEgEQgEgEAAgIQAAgHAEgEQAEgEAGAAQAIAAADAFIAAgFIAFAAIAAAdQAAAOgQAAQgFAAgEgDgAEgCBQgCADAAAFQAAAFACAEQADADAFAAQAEAAADgDQADgEAAgEQAAgFgDgEQgDgDgEAAQgFAAgDADgAFdClIAAgrIAEAAIABAFQAEgFAHAAQAGAAAEAEQAEAEAAAHQAAAHgEAFQgEAEgGAAQgIAAgDgFIAAARgAFlCBQgDADAAAFQAAAFADAEQADADAEAAQAFAAACgDQADgEAAgFQAAgFgDgDQgCgDgFAAQgEAAgDADgAiMClIAAgrIAEAAIABAFQADgFAHAAQAHAAAEAEQAEAEAAAHQAAAHgEAFQgFAEgGAAQgHAAgDgFIAAARgAiFCBQgDADAAAFQAAAFADAEQADADAFAAQAEAAADgDQADgEAAgFQAAgFgDgDQgDgDgEAAQgFAAgDADgACsCeIAEgCIABgDIAAgBIgCABQgBAAgBAAQAAAAgBgBQAAAAgBgBQAAAAAAgBIABgDIADgBQABAAAAAAQABABAAAAQABAAAAAAQAAABABAAQAAABAAAAQABABAAAAQAAABAAAAQAAABAAABQAAADgCADQgCACgEAAgAm1CeIAEgCIABgDIAAgBIgCABQgBAAgBAAQAAAAgBgBQAAAAgBgBQAAAAAAgBIABgDIADgBQABAAAAAAQABABAAAAQABAAAAAAQAAABABAAQAAABAAAAQABABAAAAQAAABAAAAQAAABAAABQAAADgCADQgCACgEAAgAKNCWQgDgDgBgFIAFAAQACAHAHAAQAFAAADgFQADgEAAgHIAAgDIAAACQgCADgDACQgDACgEAAQgGAAgEgEQgEgEAAgHQAAgGAEgEQAEgEAHAAQAIAAAEAHQAEAGAAAJQAAAKgFAFQgEAGgHAAQgGAAgEgDgAKQB2QgDACAAAEQAAAFADACQACADAFAAQAEAAADgDQACgCAAgFQAAgEgCgDQgDgCgEAAQgFAAgCADgAJVCSQgDgGAAgIQAAgKAEgGQAEgGAIAAQAFAAAEAEQAEADABAFIgFAAQgCgHgHAAQgGAAgDAEQgDAFAAAHIAAACIABgBQABgDADgCQADgCAEAAQAHAAADAEQAEAEAAAGQAAAGgEAEQgEAEgGAAQgJAAgEgHgAJbCEQgDADAAAEQAAAEADADQACADAFAAQAEAAADgDQACgDAAgEQAAgEgCgDQgDgDgEAAQgEAAgDADgAIzCWQgEgDAAgGQAAgEACgCQACgDAEgBQgDgBgCgCQgCgDAAgDQAAgFAEgEQAEgDAGAAQAGAAAEADQAEAEAAAFQAAADgCADQgCACgDABQAEABACACQACADAAAEQAAAGgEADQgEADgHAAQgHAAgEgDgAI3CIQgDACAAADQAAADADADQACACAFAAQAEAAADgCQADgDAAgDQAAgDgDgCQgDgCgEAAQgFAAgCACgAI3B1QgCABAAAEQAAADACACQADABAEAAQAEAAACgBQADgCAAgDQAAgEgDgBQgCgCgEAAQgEAAgDACgAHrCUQgEgGAAgJIAAgCQAAgJAEgGQAFgGAHAAQAHAAAEAGQAFAGAAAJIAAACQAAAJgFAGQgEAFgHAAQgHAAgFgFgAHvB3QgDAFAAAHIAAACQAAAHADAEQADAFAFAAQAFAAADgFQADgEAAgHIAAgCQAAgHgDgFQgDgEgFAAQgFAAgDAEgAG6CVQgEgFAAgHQAAgHAEgEQAEgEAGAAQAHAAADAEQAEAEABAGIgBACIgXAAIAAABQAAAEACADQADADAEAAQAEAAACgCQACgCABgDIAFAAQgBAFgDADQgEADgFAAQgHAAgEgEgAHNCGQAAgEgDgCQgCgCgEAAQgDAAgDACQgDADAAADIASAAIAAAAgAGECVQgEgFAAgHQAAgHAEgEQAEgEAHAAQAGAAAFAEQAEAEAAAHQAAAHgEAFQgFAEgGAAQgHAAgEgEgAGHCBQgCAEAAAEQAAAFACAEQADADAFAAQAEAAADgDQADgEAAgFQAAgEgDgEQgDgDgEAAQgFAAgDADgAE/CXQgDgDAAgEQAAgJAMAAIAJAAIAAgCQAAgDgCgCQgCgCgDAAQgEAAgCACQAAAAgBAAQAAABAAAAQgBABAAAAQAAABAAAAIgFAAQAAgEAEgDQADgCAGAAQAGAAADADQADACAAAGIAAANQAAABAAAAQAAABABAAQAAAAAAAAQABAAAAAAIACAAIAAAFIgDAAQgFAAAAgFQgEAFgHAAQgFAAgDgCgAFBCQQAAAAAAABQAAABAAAAQABAAAAABQAAAAABABIAFABQAEAAADgCQACgDAAgEIAAgBIgJAAQgHAAAAAFgADMCVQgEgEAAgGIAFAAQAAAEADADQADACAFAAQAFAAACgBQADgCAAgEQAAgDgDgCIgJgCQgGgBgDgCQgEgDAAgGQAAgFAEgDQAEgEAGAAQAHAAAEAEQAEADABAGIgGAAQAAgEgDgCQgDgCgEAAQgEAAgDACQgCACAAADQAAADADACIAIACQAHABADACQAEADAAAGQAAAFgEAEQgEADgHAAQgHAAgFgEgACPCXQgDgDAAgEQAAgJAMAAIAJAAIAAgCQAAgDgCgCQgCgCgDAAQgEAAgCACQAAAAgBAAQAAABAAAAQgBABAAAAQAAABAAAAIgFAAQAAgEAEgDQADgCAGAAQAGAAADADQADACAAAGIAAANQAAABAAAAQABABAAAAQAAAAAAAAQABAAAAAAIACAAIAAAFIgDAAQgFAAAAgFQgEAFgHAAQgFAAgDgCgACRCQQAAAAAAABQAAABAAAAQAAAAABABQAAAAABABIAFABQAEAAADgCQACgDAAgEIAAgBIgJAAQgHAAAAAFgABTCXQgEgDAAgEQAAgJANAAIAJAAIAAgCQAAgDgCgCQgCgCgEAAQgDAAgCACQgBAAAAAAQgBABAAAAQAAABAAAAQgBABAAAAIgFAAQABgEADgDQAEgCAFAAQAGAAADADQAEACAAAGIAAANQAAABAAAAQAAABAAAAQABAAAAAAQAAAAABAAIABAAIAAAFIgCAAQgGAAAAgFQgEAFgGAAQgFAAgDgCgABUCQQAAAAAAABQABABAAAAQAAAAAAABQABAAAAABIAFABQAFAAACgCQADgDAAgEIAAgBIgKAAQgHAAAAAFgAgKCVQgEgEAAgHQAAgIAEgEQAEgEAGAAQAFAAAEADQADADABAFIgFAAQgCgHgGAAQgEAAgDADQgCAEAAAFQAAAFACADQADADAEAAQADAAACgCQACgCABgDIAFAAQgBAFgDADQgEADgFAAQgGAAgEgEgAhDCUIgBAFIgEAAIAAgqIAFAAIAAAQQAEgFAHAAQAGAAAEAEQAEAEAAAHQAAAHgEAFQgEAEgGAAQgIAAgDgFgAhACBQgDADAAAFQAAAFADAEQADADAEAAQAFAAACgDQADgEAAgFQAAgFgDgDQgCgDgFAAQgEAAgDADgAhmCWQgDgEAAgHIAAgRIAFAAIAAARQAAAKAIAAQAEAAACgDQADgDAAgGIAAgPIAEAAIAAAfIgEAAIAAgEQgEAEgGAAQgGAAgDgDgAirCVQgEgFAAgHQAAgHAEgEQAEgEAHAAQAGAAAEAEQAEAEAAAGIAAACIgYAAIAAABQAAAEADADQADADAEAAQADAAACgCQADgCABgDIAFAAQgBAFgEADQgEADgFAAQgHAAgEgEgAiXCGQgBgEgCgCQgDgCgDAAQgEAAgCACQgDADgBADIATAAIAAAAgAkWCUQgFgGAAgJIAAgCQAAgJAFgGQAEgGAHAAQAHAAAFAGQAEAGAAAJIAAACQAAAJgEAGQgFAFgHAAQgHAAgEgFgAkTB3QgDAFAAAHIAAACQAAAHADAEQADAFAFAAQAFAAADgFQADgEAAgHIAAgCQAAgHgDgFQgDgEgFAAQgFAAgDAEgAlVCSQgDgGAAgIQAAgKAEgGQAEgGAIAAQAFAAAEAEQAEADABAFIgFAAQgCgHgHAAQgGAAgDAEQgDAFAAAHIAAACIABgBQABgDADgCQADgCAEAAQAHAAADAEQAEAEAAAGQAAAGgEAEQgEAEgGAAQgJAAgEgHgAlPCEQgDADAAAEQAAAEADADQACADAFAAQAEAAADgDQACgDAAgEQAAgEgCgDQgDgDgEAAQgEAAgDADgAnSCVQgEgFAAgHQAAgHAEgEQAEgEAGAAQAHAAADAEQAEAEABAGIgBACIgXAAIAAABQAAAEACADQADADAEAAQAEAAACgCQACgCABgDIAFAAQgBAFgDADQgEADgFAAQgHAAgEgEgAm/CGQAAgEgDgCQgCgCgEAAQgDAAgDACQgDADAAADIASAAIAAAAgAnzCVQgEgEAAgHQAAgIAEgEQAEgEAHAAQAGAAADADQAEADAAAFIgFAAQgBgHgHAAQgEAAgDADQgDAEAAAFQAAAFADADQACADAFAAQADAAACgCQADgCAAgDIAFAAQAAAFgEADQgEADgFAAQgHAAgEgEgAoUCXQgDgDAAgEQAAgJAMAAIAJAAIAAgCQAAgDgCgCQgCgCgDAAQgEAAgCACQAAAAgBAAQAAABAAAAQgBABAAAAQAAABAAAAIgFAAQAAgEAEgDQADgCAGAAQAGAAADADQADACAAAGIAAANQAAABAAAAQABABAAAAQAAAAAAAAQABAAAAAAIACAAIAAAFIgDAAQgFAAAAgFQgEAFgHAAQgFAAgDgCgAoSCQQAAAAAAABQAAABAAAAQABAAAAABQAAAAABABIAFABQAEAAADgCQACgDAAgEIAAgBIgJAAQgHAAAAAFgApvCWQgEgCAAgFIAFAAQAAACACACQADACADAAIAGgBQAAgBABAAQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAAAgBQgBAAAAgBQAAAAgBgBQAAAAgBAAIgFgBIgJgDQgDgCAAgEQAAgEADgDQADgCAGAAQAFAAADACQAEADAAAEIgFAAQAAAAAAgBQgBAAAAgBQAAAAAAAAQgBgBAAAAQgCgCgDAAIgGABQAAAAgBABQAAAAAAABQgBAAAAABQAAAAAAABQAAAAAAABQABAAAAAAQAAABABAAQAAABABAAIAFABIAJACQAEACAAAFQAAAEgEADQgDACgGAAQgGAAgDgDgAqQCVQgEgFAAgHQAAgHAEgEQAEgEAGAAQAHAAADAEQAEAEABAGIgBACIgXAAIAAABQAAAEACADQADADAEAAQAEAAACgCQACgCABgDIAFAAQgBAFgDADQgEADgFAAQgHAAgEgEgAp9CGQAAgEgDgCQgCgCgEAAQgDAAgDACQgDADAAADIASAAIAAAAgArjCXQgDgDAAgEQAAgJAMAAIAJAAIAAgCQAAgDgCgCQgCgCgDAAQgEAAgCACQAAAAgBAAQAAABAAAAQgBABAAAAQAAABAAAAIgFAAQAAgEAEgDQADgCAGAAQAGAAADADQADACAAAGIAAANQAAABAAAAQABABAAAAQAAAAAAAAQABAAAAAAIACAAIAAAFIgDAAQgFAAAAgFQgEAFgHAAQgFAAgDgCgArhCQQAAAAAAABQAAABAAAAQABAAAAABQAAAAABABIAFABQAEAAADgCQACgDAAgEIAAgBIgJAAQgHAAAAAFgAs4CWQgEgDgBgFIAFAAQACAHAHAAQAGAAADgFQADgEAAgHIAAgDIgBACQgBADgDACQgDACgEAAQgHAAgDgEQgEgEAAgHQAAgGAEgEQAEgEAGAAQAJAAAEAHQADAGAAAJQAAAKgEAFQgEAGgIAAQgFAAgEgDgAs2B2QgCACAAAEQAAAFACACQADADAEAAQAEAAADgDQADgCAAgFQAAgEgDgDQgCgCgFAAQgEAAgDADgAJ9CZIAAgeIgDAAIgHAAIAAgEIAHAAQAAAAABAAQABgBAAAAQAAgBABAAQAAgBAAgBIAAgEIAFAAIAAAqgAIgCZIAAgLIgWAAIAAgEIAVgbIAGAAIAAAbIAHAAIAAAEIgHAAIAAALgAIQCKIAQAAIAAgVgAGjCZIAAgfIAEAAIABAFQADgFAGAAIACAAIAAAFIgDAAQgEAAgCADQgCADAAAEIAAAQgAEPCZIAAgRQAAgKgJAAQgEAAgCADQgDADAAAFIAAAQIgFAAIAAgfIAEAAIABAEQADgEAHAAQAGAAADADQADAEAAAHIAAARgADtCZIAAgfIAFAAIAAAfgABvCZIAAgEIASgWIgSAAIAAgFIAZAAIAAAEIgTAWIATAAIAAAFgABFCZIAAgqIAFAAIAAAqgAAiCZIAAgqIAQAAQAHAAAEADQADAEAAAGQAAAGgDADQgEAEgHAAIgKAAIAAAQgAAoCEIAKAAQAEAAADgCQACgDAAgDQAAgEgCgCQgDgCgEAAIgKAAgAgZCZIAAgfIAFAAIAAAfgAgkCZIAAgqIAFAAIAAAqgAi5CZIgJgQIgKAAIAAAQIgGAAIAAgqIAQAAQAHAAAEADQADAEAAAGQAAAEgCADQgCADgFACIAKARgAjMCEIAKAAQAEAAADgCQACgDAAgDQAAgEgCgCQgDgCgEAAIgKAAgAjuCZIAAgeIgDAAIgHAAIAAgEIAHAAQAAAAABAAQABgBAAAAQAAgBABAAQAAgBAAgBIAAgEIAFAAIAAAqgAl5CZIAAgEIAQgPIAFgFQACgDAAgDQAAgEgCgCQgDgCgEAAQgEAAgDACQgCADAAAEIAAABIgFAAIAAgBQAAgGAEgEQAEgEAGAAQAHAAADAEQAEADAAAGQAAAEgCAEIgHAGIgMALIAVAAIAAAFgAmOCZIAEgNIgHAAIgDANIgEAAIADgNIgHAAIABgEIAHAAIADgKIgHAAIABgDIAHAAIADgNIAEAAIgDANIAGAAIAEgNIAEAAIgDANIAHAAIgBADIgHAAIgDAKIAHAAIgBAEIgHAAIgDANgAmQCIIAHAAIADgKIgHAAgAohCZIAAgqIAFAAIAAAqgApECZIAAgqIAQAAQAGAAAEADQAEAEAAAGQAAAGgEADQgEAEgGAAIgLAAIAAAQgAo/CEIAKAAQAFAAACgCQADgDAAgDQAAgEgDgCQgCgCgEAAIgLAAgAqfCZIAAgqIAFAAIAAAqgAqwCZIAAgaIgOAAIAAAaIgFAAIAAgaIgFAAIAAgFIAFAAIAAgDQAAgEACgCQACgCAEAAIAGAAIAAAEIgFAAQgBAAgBAAQAAABgBAAQAAABgBAAQAAABAAABIAAADIAOAAIAAgDQAAgEACgCQACgCAEAAIAGAAIAAAEIgFAAQgBAAgBAAQAAABgBAAQAAABgBAAQAAABAAABIAAADIAJAAIAAAFIgJAAIAAAagArwCZIgJgQIgKAAIAAAQIgGAAIAAgqIAQAAQAHAAAEADQADAEAAAGQAAAEgCADQgCADgFACIAKARgAsDCEIAKAAQAEAAADgCQACgDAAgDQAAgEgCgCQgDgCgEAAIgKAAgAk0CKIAAgEIAUAAIAAAEgADtB0IgBgCIABgCIACgBIACABIABACIgBACIgCABIgCgBgAgZB0IgBgCIABgCIADgBIACABIABACIgBACIgCABIgDgBgAkPBKQgEgDgBgFIAFAAQACAGAIAAQAKAAAAgJIAAgEQgEAGgHAAQgGAAgEgEQgEgFAAgHQAAgHAEgEQAEgFAGAAQAIAAADAGIAAgFIAFAAIAAAdQAAAOgQAAQgFAAgEgDgAkNApQgCADAAAFQAAAFACADQADADAFAAQAEAAADgDQADgDAAgFQAAgFgDgDQgDgDgEAAQgFAAgDADgAjQBMIAAgqIAEAAIABAFQAEgGAHAAQAGAAAEAEQAEAFAAAHQAAAHgEAEQgEAFgGAAQgIAAgDgFIAAAQgAjIApQgDADAAAFQAAAFADADQADADAEAAQAFAAACgDQADgDAAgFQAAgFgDgDQgCgDgFAAQgEAAgDADgACCBAIAAgDIAAgCIADgBIACABIABACIgBADIgCABIgDgBgABiA9QgEgFAAgHQAAgHAEgEQAEgFAGAAQAIAAADAFIAAgQIAFAAIAAAqIgFAAIAAgFQgEAGgHAAQgGAAgEgEgABlApQgCADAAAFQAAAFACADQADADAFAAQAEAAADgDQADgDAAgFQAAgFgDgDQgDgDgEAAQgFAAgDADgAASBAIAAgDIAAgCIADgBIACABIABACIgBADIgCABIgDgBgAgLA8QgEgEAAgHQAAgHAEgEQAEgFAGAAQAGAAADAEQAEAEABAHIgBACIgWAAIAAAAQAAAFACACQADADAEAAQADAAACgBQACgCABgDIAFAAQgBAFgDADQgEADgEAAQgHAAgEgFgAAHAuQAAgEgDgCQgCgCgDAAQgDAAgDACQgDACAAAEIARAAIAAAAgAhzA8QgEgEAAgHQAAgHAEgEQAEgFAGAAQAHAAADAEQAEAEABAHIgBACIgXAAIAAAAQAAAFACACQADADAEAAQAEAAACgBQACgCABgDIAFAAQgBAFgDADQgEADgFAAQgHAAgEgFgAhgAuQAAgEgDgCQgCgCgEAAQgDAAgDACQgDACAAAEIASAAIAAAAgAipA8QgEgEAAgHQAAgHAEgEQAEgFAHAAQAGAAAFAFQAEAEAAAHQAAAHgEAEQgFAFgGAAQgHAAgEgFgAimApQgCADAAAFQAAAFACADQADADAFAAQAEAAADgDQADgDAAgFQAAgFgDgDQgDgDgEAAQgFAAgDADgAjuA+QgDgCAAgEQAAgKAMAAIAJAAIAAgCQAAgDgCgCQgCgBgDAAQgEAAgCABQAAABgBAAQAAAAAAABQgBAAAAABQAAAAAAABIgFAAQAAgFAEgCQADgDAGAAQAGAAADADQADADAAAFIAAAOQAAAAAAABQAAAAABAAQAAAAAAABQABAAAAAAIACAAIAAAEIgDAAQgFAAAAgEQgEAFgHAAQgFAAgDgDgAjsA3QAAABAAAAQAAABAAABQABAAAAAAQAAABABAAIAFABQAEAAADgCQACgCAAgEIAAgCIgJAAQgHAAAAAFgAlhA9QgEgEAAgGIAFAAQAAAEADACQADADAFAAQAFAAACgCQADgCAAgDQAAgEgDgCIgJgCQgGgBgDgCQgEgDAAgFQAAgGAEgDQAEgDAGAAQAHAAAEADQAEAEABAGIgGAAQAAgEgDgCQgDgCgEAAQgEAAgDABQgCACAAAEQAAADADACIAIACQAHABADACQAEADAAAFQAAAGgEADQgEAEgHAAQgHAAgFgEgAmzA8QgEgEAAgHQAAgHAEgEQAEgFAHAAQAGAAADADQAEADAAAFIgFAAQgBgGgHAAQgEAAgDADQgDADAAAFQAAAFADADQACADAFAAQADAAACgCQADgBAAgDIAFAAQAAAFgEADQgEADgFAAQgHAAgEgFgAnUA8QgEgEAAgHQAAgHAEgEQAEgFAGAAQAHAAADAEQAEAEABAHIgBACIgXAAIAAAAQAAAFACACQADADAEAAQAEAAACgBQACgCABgDIAFAAQgBAFgDADQgEADgFAAQgHAAgEgFgAnBAuQAAgEgDgCQgCgCgEAAQgDAAgDACQgDACAAAEIASAAIAAAAgAoKA8QgEgEAAgHQAAgHAEgEQAEgFAHAAQAGAAAFAFQAEAEAAAHQAAAHgEAEQgFAFgGAAQgHAAgEgFgAoHApQgCADAAAFQAAAFACADQADADAFAAQAEAAADgDQADgDAAgFQAAgFgDgDQgDgDgEAAQgFAAgDADgAprA+QgEgCAAgEQAAgKANAAIAJAAIAAgCQAAgDgCgCQgCgBgEAAQgDAAgCABQgBABAAAAQgBAAAAABQAAAAAAABQgBAAAAABIgFAAQABgFADgCQAEgDAFAAQAGAAADADQAEADAAAFIAAAOQAAAAAAABQAAAAAAAAQABAAAAABQAAAAABAAIABAAIAAAEIgCAAQgGAAAAgEQgEAFgGAAQgFAAgDgDgApqA3QAAABAAAAQABABAAABQAAAAAAAAQABABAAAAIAFABQAFAAACgCQADgCAAgEIAAgCIgKAAQgHAAAAAFgArBA8QgEgEAAgHQAAgHAEgEQAEgFAHAAQAGAAAEAEQAEAEAAAHIAAACIgYAAIAAAAQAAAFADACQADADAEAAQADAAACgBQADgCABgDIAFAAQgBAFgEADQgEADgFAAQgHAAgEgFgAqtAuQgBgEgCgCQgDgCgDAAQgEAAgCACQgDACgBAEIATAAIAAAAgArkA9QgEgFAAgHQAAgHAEgEQAEgFAGAAQAIAAADAFIAAgQIAFAAIAAAqIgFAAIAAgFQgEAGgHAAQgGAAgEgEgArhApQgCADAAAFQAAAFACADQADADAFAAQAEAAADgDQADgDAAgFQAAgFgDgDQgDgDgEAAQgFAAgDADgAsHA8QgEgEAAgHQAAgHAEgEQAFgFAGAAQAHAAAEAFQAEAEAAAHQAAAHgEAEQgEAFgHAAQgGAAgFgFgAsDApQgDADAAAFQAAAFADADQADADAEAAQAFAAADgDQACgDAAgFQAAgFgCgDQgDgDgFAAQgEAAgDADgABVBAQgEAAgCgCQgCgCAAgEIAAgSIgFAAIAAgEIAFAAIAAgJIAFAAIAAAJIAIAAIAAAEIgIAAIAAASIABADIADABIAFAAIAAAEgAAuBAIAAgqIAGAAIAAAlIATAAIAAAFgAgYBAQgEAAgCgCQgCgCAAgEIAAgSIgFAAIAAgEIAFAAIAAgJIAFAAIAAAJIAIAAIAAAEIgIAAIAAASIABADIADABIAFAAIAAAEgAhFBAIAAgqIAQAAQAHAAAEAEQADADAAAGQAAAGgDAEQgEADgHAAIgKAAIAAAQgAg/ArIAKAAQAEAAADgCQACgCAAgEQAAgEgCgCQgDgCgEAAIgKAAgAiKBAIAAgeIAEAAIABAEQADgEAGAAIACAAIAAAEIgDAAQgEAAgCAEQgCACAAAFIAAAPgAkeBAIAAgQQAAgKgJAAQgEAAgCADQgDADAAAFIAAAPIgFAAIAAgeIAEAAIABAEQADgFAHAAQAGAAADADQADAEAAAHIAAARgAlABAIAAgeIAFAAIAAAegAl/BAIAAgQQAAgKgIAAQgFAAgCADQgCADAAAFIAAAPIgFAAIAAgqIAFAAIAAARQADgGAHAAQAFAAADADQAEAEAAAHIAAARgAnhBAQgEAAgCgCQgCgCAAgEIAAgSIgFAAIAAgEIAFAAIAAgJIAFAAIAAAJIAIAAIAAAEIgIAAIAAASIABADIADABIAFAAIAAAEgAoZBAIAAgeIAFAAIAAAegAo9BAIAAgqIAPAAQAGAAAEADQAEADAAAFQAAAHgHACQAIACAAAIQAAAGgEADQgEADgHAAgAo4A8IAKAAQAFAAACgCQADgCAAgDQAAgEgDgCQgCgCgFAAIgKAAgAo4AoIAKAAQAEAAACgBQACgCAAgDQAAgDgCgCQgCgCgEAAIgKAAgAp4BAIAAgQQAAgKgJAAQgEAAgCADQgDADAAAFIAAAPIgFAAIAAgeIAEAAIABAEQADgFAHAAQAGAAADADQADAEAAAHIAAARgAqiBAIAAgeIAEAAIABAEQACgEAHAAIABAAIAAAEIgCAAQgFAAgCAEQgBACAAAFIAAAPgAsWBAIAAghIgOAhIgFAAIgOghIAAAhIgFAAIAAgqIAHAAIAPAjIAPgjIAGAAIAAAqgAlAAcIgBgDIABgCIACgBIACABIABACIgBADIgCAAIgCAAgAoZAcIgBgDIABgCIADgBIACABIABACIgBADIgCAAIgDAAgAAAhkIAAgqIAEAAIABAFQADgGAHAAQAHAAAEAEQAEAFAAAHQAAAHgEAEQgFAFgGAAQgHAAgDgFIAAAQgAAHiHQgDADAAAFQAAAFADADQADADAFAAQAEAAADgDQADgDAAgFQAAgFgDgDQgDgDgEAAQgFAAgDADgAmthkIAAgEIAEAAIADgBIACgDIABgEIgMgeIAFAAIAKAYIAJgYIAFAAIgOAjIgDAGQAAAAgBAAQAAABgBAAQAAAAgBAAQAAAAgBAAgAM6hwIgBgDIABgCIACgBIADABIABACIgBADIgDABIgCgBgAMbh0QgEgEAAgHQAAgHAEgEQAEgFAHAAQAGAAAEAEQAEAEAAAHIAAACIgYAAIAAAAQAAAFADACQADADAEAAQADAAACgBQADgCABgDIAFAAQgBAFgEADQgEADgFAAQgHAAgEgFgAMviCQgBgEgCgCQgDgCgDAAQgEAAgCACQgDACgBAEIATAAIAAAAgAL7h0QgEgEAAgHQAAgHAEgEQAEgFAGAAQAGAAAEADQADADABAFIgFAAQgCgGgHAAQgEAAgDADQgCADAAAFQAAAFACADQADADAEAAQAEAAACgCQACgBABgDIAFAAQgBAFgDADQgEADgGAAQgGAAgEgFgAKvhzQgEgFAAgHQAAgHAEgEQAEgFAGAAQAIAAADAFIAAgQIAFAAIAAAqIgFAAIAAgFQgEAGgHAAQgGAAgEgEgAKyiHQgCADAAAFQAAAFACADQADADAFAAQAEAAADgDQADgDAAgFQAAgFgDgDQgDgDgEAAQgFAAgDADgAKOhyQgEgCAAgEQAAgKANAAIAJAAIAAgCQAAgDgCgCQgCgBgEAAQgDAAgCABQgBAAAAABQgBAAAAABQAAAAAAABQgBAAAAABIgFAAQABgFADgCQAEgDAFAAQAGAAADADQAEADAAAFIAAAOQAAAAAAABQAAAAAAAAQAAABABAAQAAAAABAAIABAAIAAAEIgCAAQgGAAAAgEQgEAFgGAAQgFAAgDgDgAKPh5QAAABAAAAQAAABABAAQAAABAAAAQABABAAAAIAFABQAFAAACgCQADgCAAgEIAAgCIgKAAQgHAAAAAFgAJThyQgEgCAAgEQAAgKANAAIAJAAIAAgCQAAgDgCgCQgCgBgEAAQgDAAgCABQgBAAAAABQgBAAAAABQAAAAAAABQgBAAAAABIgFAAQABgFADgCQAEgDAFAAQAGAAADADQAEADAAAFIAAAOQAAAAAAABQAAAAAAAAQABABAAAAQAAAAABAAIABAAIAAAEIgCAAQgGAAAAgEQgEAFgGAAQgFAAgDgDgAJUh5QAAABAAAAQABABAAAAQAAABAAAAQABABAAAAIAFABQAFAAACgCQADgCAAgEIAAgCIgKAAQgHAAAAAFgAIzh0QgEgEAAgHQAAgHAEgEQAEgFAHAAQAGAAADADQAEADAAAFIgFAAQgBgGgHAAQgEAAgDADQgDADAAAFQAAAFADADQACADAFAAQADAAACgCQADgBAAgDIAFAAQAAAFgEADQgEADgFAAQgHAAgEgFgAIEhzQgEgFAAgHQAAgHAEgEQAEgFAHAAQAHAAADAFIAAgQIAFAAIAAAqIgEAAIgBgFQgEAGgGAAQgHAAgEgEgAIIiHQgDADAAAFQAAAFADADQADADAEAAQAFAAADgDQACgDAAgFQAAgFgCgDQgDgDgFAAQgEAAgDADgAHjh0QgEgEAAgHQAAgHAEgEQAEgFAGAAQAHAAADAEQAEAEABAHIgBACIgXAAIAAAAQAAAFACACQADADAEAAQAEAAACgBQACgCABgDIAFAAQgBAFgDADQgEADgFAAQgHAAgEgFgAH2iCQAAgEgDgCQgCgCgEAAQgDAAgDACQgDACAAAEIASAAIAAAAgAFph0QgEgEAAgHQAAgHAEgEQAFgFAGAAQAHAAAEAFQAEAEAAAHQAAAHgEAEQgEAFgHAAQgGAAgFgFgAFtiHQgDADAAAFQAAAFADADQADADAEAAQAFAAADgDQACgDAAgFQAAgFgCgDQgDgDgFAAQgEAAgDADgAEahyQgDgCAAgEQAAgKAMAAIAJAAIAAgCQAAgDgCgCQgCgBgDAAQgEAAgCABQAAAAgBABQAAAAAAABQgBAAAAABQAAAAAAABIgFAAQAAgFAEgCQADgDAGAAQAGAAADADQADADAAAFIAAAOQAAAAAAABQAAAAABAAQAAABAAAAQABAAAAAAIACAAIAAAEIgDAAQgFAAAAgEQgEAFgHAAQgFAAgDgDgAEch5QAAABAAAAQAAABAAAAQABABAAAAQAAABABAAIAFABQAEAAADgCQACgCAAgEIAAgCIgJAAQgHAAAAAFgADXh0QgEgEAAgHQAAgHAEgEQAFgFAGAAQAHAAAEAFQAEAEAAAHQAAAHgEAEQgEAFgHAAQgGAAgFgFgADbiHQgDADAAAFQAAAFADADQADADAEAAQAFAAADgDQACgDAAgFQAAgFgCgDQgDgDgFAAQgEAAgDADgACuhyQgEgDAAgFIAFAAQAAADACACQADABADAAIAGgBQAAAAABgBQAAAAAAAAQAAgBABAAQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAgBgBAAIgFgBIgJgCQgDgCAAgFQAAgEADgCQADgDAGAAQAFAAADADQAEACAAAFIgFAAQAAgBAAAAQAAgBgBAAQAAgBAAAAQgBAAAAgBQgCgBgDAAIgGABQAAAAgBAAQAAABAAAAQAAABgBAAQAAABAAAAQAAABAAAAQABABAAAAQAAAAABABQAAAAABAAIAFABIAJADQAEACAAAEQAAAFgEACQgDADgGAAQgGAAgDgDgACQhyQgEgDAAgFIAFAAQABADACACQACABAEAAIAFgBQABAAAAgBQAAAAABAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQgBgBAAAAQgBgBAAAAIgGgBIgIgCQgEgCAAgFQAAgEADgCQAEgDAFAAQAFAAAEADQADACAAAFIgFAAQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAAAgBgBQgCgBgDAAIgFABQgBAAAAAAQgBABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQABAAAAABQABAAAAAAIAGABIAIADQAEACAAAEQAAAFgDACQgEADgFAAQgGAAgEgDgABvh0QgEgEAAgHQAAgHAEgEQAEgFAHAAQAGAAAEAEQAEAEAAAHIAAACIgYAAIAAAAQAAAFADACQADADAEAAQADAAACgBQADgCABgDIAFAAQgBAFgEADQgEADgFAAQgHAAgEgFgACDiCQgBgEgCgCQgDgCgDAAQgEAAgCACQgDACgBAEIATAAIAAAAgAA6h0QgEgEAAgHQAAgHAEgEQAEgFAHAAQAGAAAFAFQAEAEAAAHQAAAHgEAEQgFAFgGAAQgHAAgEgFgAA9iHQgCADAAAFQAAAFACADQADADAFAAQAEAAADgDQADgDAAgFQAAgFgDgDQgDgDgEAAQgFAAgDADgAgth0QgEgEAAgHQAAgHAEgEQAEgFAGAAQAHAAADAEQAEAEABAHIgBACIgXAAIAAAAQAAAFACACQADADAEAAQAEAAACgBQACgCABgDIAFAAQgBAFgDADQgEADgFAAQgHAAgEgFgAgaiCQAAgEgDgCQgCgCgEAAQgDAAgDACQgDACAAAEIASAAIAAAAgAhihyQgDgCAAgEQAAgKAMAAIAJAAIAAgCQAAgDgCgCQgCgBgDAAQgEAAgCABQAAAAgBABQAAAAAAABQgBAAAAABQAAAAAAABIgFAAQAAgFAEgCQADgDAGAAQAGAAADADQADADAAAFIAAAOQAAAAAAABQAAAAABAAQAAABAAAAQABAAAAAAIACAAIAAAEIgDAAQgFAAAAgEQgEAFgHAAQgFAAgDgDgAhgh5QAAABAAAAQAAABAAAAQAAABABAAQAAABABAAIAFABQAEAAADgCQACgCAAgEIAAgCIgJAAQgHAAAAAFgAiBh0QgEgEAAgHQAAgHAEgEQAEgFAGAAQAGAAAEADQADADABAFIgFAAQgCgGgHAAQgEAAgDADQgCADAAAFQAAAFACADQADADAEAAQAEAAACgCQACgBABgDIAFAAQgBAFgDADQgEADgGAAQgGAAgEgFgAjjhyQgDgCAAgEQAAgKAMAAIAJAAIAAgCQAAgDgCgCQgCgBgDAAQgEAAgCABQAAAAgBABQAAAAAAABQgBAAAAABQAAAAAAABIgFAAQAAgFAEgCQADgDAGAAQAGAAADADQADADAAAFIAAAOQAAAAAAABQABAAAAAAQAAABAAAAQABAAAAAAIACAAIAAAEIgDAAQgFAAAAgEQgEAFgHAAQgFAAgDgDgAjhh5QAAABAAAAQAAABAAAAQABABAAAAQAAABABAAIAFABQAEAAADgCQACgCAAgEIAAgCIgJAAQgHAAAAAFgAkDh0QgEgEAAgHQAAgHAEgEQAEgFAGAAQAHAAADAEQAEAEABAHIgBACIgXAAIAAAAQAAAFACACQADADAEAAQAEAAACgBQACgCABgDIAFAAQgBAFgDADQgEADgFAAQgHAAgEgFgAjwiCQAAgEgDgCQgCgCgEAAQgDAAgDACQgDACAAAEIASAAIAAAAgAlphzQgDgDAAgHIAAgRIAFAAIAAAQQAAAKAIAAQAEAAACgDQADgDAAgFIAAgPIAEAAIAAAeIgEAAIAAgEQgEAFgGAAQgGAAgDgEgAmLh0QgEgEAAgHQAAgHAEgEQAEgFAHAAQAGAAAFAFQAEAEAAAHQAAAHgEAEQgFAFgGAAQgHAAgEgFgAmIiHQgCADAAAFQAAAFACADQADADAFAAQAEAAADgDQADgDAAgFQAAgFgDgDQgDgDgEAAQgFAAgDADgAn4hzQgEgDAAgHIAAgRIAFAAIAAAQQAAAKAIAAQAEAAADgDQACgDAAgFIAAgPIAFAAIAAAeIgEAAIgBgEQgDAFgHAAQgFAAgDgEgAoWhyQgEgDAAgFIAFAAQAAADACACQADABADAAIAGgBQAAAAABgBQAAAAAAAAQAAgBABAAQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAgBgBAAIgFgBIgJgCQgDgCAAgFQAAgEADgCQADgDAGAAQAFAAADADQAEACAAAFIgFAAQAAgBAAAAQgBgBAAAAQAAgBAAAAQgBAAAAgBQgCgBgDAAIgGABQAAAAgBAAQAAABAAAAQgBABAAAAQAAABAAAAQAAABAAAAQABABAAAAQAAAAABABQAAAAABAAIAFABIAJADQAEACAAAEQAAAFgEACQgDADgGAAQgGAAgDgDgApah0QgEgEAAgHQAAgHAEgEQAFgFAGAAQAHAAAEAFQAEAEAAAHQAAAHgEAEQgEAFgHAAQgGAAgFgFgApWiHQgDADAAAFQAAAFADADQADADAEAAQAFAAADgDQACgDAAgFQAAgFgCgDQgDgDgFAAQgEAAgDADgAp6h0QgEgEAAgHQAAgHAEgEQAEgFAGAAQAGAAAEADQADADABAFIgFAAQgCgGgHAAQgEAAgDADQgCADAAAFQAAAFACADQADADAEAAQAEAAACgCQACgBABgDIAFAAQgBAFgDADQgEADgGAAQgGAAgEgFgAqrh0QgEgEAAgHQAAgHAEgEQAEgFAGAAQAHAAADAEQAEAEABAHIgBACIgXAAIAAAAQAAAFACACQADADAEAAQAEAAACgBQACgCABgDIAFAAQgBAFgDADQgEADgFAAQgHAAgEgFgAqYiCQAAgEgDgCQgCgCgEAAQgDAAgDACQgDACAAAEIASAAIAAAAgArJhyQgEgDAAgFIAFAAQAAADACACQADABADAAIAGgBQAAAAABgBQAAAAAAAAQAAgBABAAQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAgBgBAAIgFgBIgJgCQgDgCAAgFQAAgEADgCQADgDAGAAQAFAAADADQAEACAAAFIgFAAQAAgBAAAAQgBgBAAAAQAAgBAAAAQgBAAAAgBQgCgBgDAAIgGABQAAAAgBAAQAAABAAAAQgBABAAAAQAAABAAAAQAAABAAAAQABABAAAAQAAAAABABQAAAAABAAIAFABIAJADQAEACAAAEQAAAFgEACQgDADgGAAQgGAAgDgDgArqhyQgDgCAAgEQAAgKAMAAIAJAAIAAgCQAAgDgCgCQgCgBgDAAQgEAAgCABQAAAAgBABQAAAAAAABQgBAAAAABQAAAAAAABIgFAAQAAgFAEgCQADgDAGAAQAGAAADADQADADAAAFIAAAOQAAAAAAABQAAAAABAAQAAABAAAAQABAAAAAAIACAAIAAAEIgDAAQgFAAAAgEQgEAFgHAAQgFAAgDgDgAroh5QAAABAAAAQAAABAAAAQAAABABAAQAAABABAAIAFABQAEAAADgCQACgCAAgEIAAgCIgJAAQgHAAAAAFgAsKh0QgEgEAAgHQAAgHAEgEQAEgFAGAAQAHAAADAEQAEAEABAHIgBACIgXAAIAAAAQAAAFACACQADADAEAAQAEAAACgBQACgCABgDIAFAAQgBAFgDADQgEADgFAAQgHAAgEgFgAr3iCQAAgEgDgCQgCgCgEAAQgDAAgDACQgDACAAAEIASAAIAAAAgALshwIAAgeIAFAAIAAAegALXhwIgLgeIAFAAIAKAZIAJgZIAFAAIgMAegAJxhwIAAgqIAFAAIAAAqgAIlhwIAAgeIAFAAIAAAegAHUhwIAAgRQAAgJgHAAQgEAAgCACQgCADAAAFIAAAQIgFAAIAAgRQAAgJgHAAQgEAAgCADQgCACAAAFIAAAQIgFAAIAAgeIAEAAIABAEQADgFAFAAQAIAAACAGQADgGAIAAQAFAAADADQADAEAAAHIAAARgAGJhwIAAgeIAEAAIABAEQACgEAHAAIABAAIAAAEIgCAAQgFAAgCAEQgBACAAAFIAAAPgAFVhwIAAgaIgFAAIAAgEIAFAAIAAgEQAAgEACgCQACgCAEAAIAGAAIAAAFIgFAAQgBAAgBAAQAAAAgBABQAAAAgBABQAAAAAAABIAAAEIAJAAIAAAEIgJAAIAAAagAE4hwIAAgqIAFAAIAAAqgAENhwIAAgQQAAgKgIAAQgFAAgCADQgCADAAAFIAAAPIgFAAIAAgeIAEAAIABAEQADgFAHAAQAFAAADADQAEAEAAAHIAAARgADJhwIAAgeIAFAAIAAAegABbhwIAAgaIgFAAIAAgEIAFAAIAAgEQAAgEACgCQACgCAEAAIAGAAIAAAFIgFAAQgBAAgBAAQAAAAgBABQAAAAgBABQAAAAAAABIAAAEIAJAAIAAAEIgJAAIAAAagAAjhwIAAgeIAEAAIABAEQADgEAGAAIACAAIAAAEIgDAAQgEAAgCAEQgCACAAAFIAAAPgAhEhwIAAgeIAEAAIABAEQADgEAGAAIACAAIAAAEIgDAAQgEAAgCAEQgCACAAAFIAAAPgAiPhwIAAgQQAAgKgJAAQgEAAgCADQgDADAAAFIAAAPIgFAAIAAgqIAFAAIAAARQADgGAHAAQAGAAADADQAEAEAAAHIAAARgAivhwQgEAAgCgCQgCgCAAgEIAAgSIgGAAIAAgEIAGAAIAAgJIAFAAIAAAJIAIAAIAAAEIgIAAIAAASIABADIACABIAFAAIAAAEgAjFhwIAAgqIAFAAIAAAqgAkRhwIAAgQQAAgKgJAAQgEAAgCADQgDADAAAFIAAAPIgFAAIAAgqIAFAAIAAARQADgGAHAAQAGAAADADQAEAEAAAHIAAARgAlLhwIAAgeIAEAAIABAEQADgEAGAAIACAAIAAAEIgDAAQgEAAgCAEQgCACAAAFIAAAPgAnFhwQgEAAgCgCQgCgCAAgEIAAgSIgFAAIAAgEIAFAAIAAgJIAFAAIAAAJIAIAAIAAAEIgIAAIAAASIABADIADABIAFAAIAAAEgAnahwIAAgqIAFAAIAAAqgAokhwIAAgQQAAgKgIAAQgFAAgCADQgCADAAAFIAAAPIgFAAIAAgeIAEAAIABAEQADgFAHAAQAFAAADADQAEAEAAAHIAAARgAsZhwIAAgqIAFAAIAAAqgAs8hwIAAgqIAQAAQAHAAAEAEQADADAAAGQAAAGgDAEQgEADgHAAIgKAAIAAAQgAs2iFIAKAAQAEAAADgCQACgCAAgEQAAgEgCgCQgDgCgEAAIgKAAgALsiUIgBgDIABgCIADgBIACABIABACIgBADIgCAAIgDAAgAIliUIgBgDIABgCIACgBIACABIABACIgBADIgCAAIgCAAgADJiUIgBgDIABgCIACgBIACABIABACIgBADIgCAAIgCAAgAEki8IAAgFIAFAAIACAAIACgDIABgEIgLgfIAFAAIAJAZIAJgZIAGAAIgPAkIgCAFQgBABAAAAQgBAAAAAAQgBABAAAAQgBAAgBAAgAAki8IAAgrIAEAAIABAFQAEgFAHAAQAGAAAEAEQAEAEAAAHQAAAHgEAFQgEAEgGAAQgIAAgDgFIAAARgAAsjgQgDADAAAFQAAAFADAEQADADAEAAQAFAAACgDQADgEAAgFQAAgFgDgDQgCgDgFAAQgEAAgDADgAgzi8IAAgrIAEAAIABAFQAEgFAHAAQAGAAAEAEQAEAEAAAHQAAAHgEAFQgEAEgGAAQgIAAgDgFIAAARgAgrjgQgDADAAAFQAAAFADAEQADADAEAAQAFAAACgDQADgEAAgFQAAgFgDgDQgCgDgFAAQgEAAgDADgAFDjJIAAgCIAAgDIADgBIACABIABADIgBACIgCABIgDgBgADZjMQgEgFAAgHQAAgHAEgEQAFgEAGAAQAHAAAEAEQAEAEAAAHQAAAHgEAFQgEAEgHAAQgGAAgFgEgADdjgQgDAEAAAEQAAAFADAEQADADAEAAQAFAAADgDQACgEAAgFQAAgEgCgEQgDgDgFAAQgEAAgDADgACsjLQgEgCAAgFIAFAAQAAACACACQADACADAAIAGgBQAAgBABAAQAAAAAAgBQABAAAAgBQAAAAAAgBQAAAAAAgBQgBAAAAgBQAAAAgBgBQAAAAgBAAIgFgBIgJgDQgDgCAAgEQAAgEADgDQADgCAGAAQAFAAADACQAEADAAAEIgFAAQAAAAAAgBQAAAAgBgBQAAAAAAAAQgBgBAAAAQgCgCgDAAIgGABQAAAAgBABQAAAAAAABQAAAAgBABQAAAAAAABQAAAAAAABQABAAAAAAQAAABABAAQAAAAABABIAFABIAJACQAEACAAAFQAAAEgEADQgDACgGAAQgGAAgDgDgACLjMQgEgFAAgHQAAgHAEgEQAEgEAGAAQAHAAADAEQAEAEABAGIgBACIgXAAIAAABQAAAEACADQADADAEAAQAEAAACgCQACgCABgDIAFAAQgBAFgDADQgEADgFAAQgHAAgEgEgACejbQAAgEgDgCQgCgCgEAAQgDAAgDACQgDADAAADIASAAIAAAAgABtjLQgEgCAAgFIAFAAQAAACACACQADACADAAIAGgBQAAgBABAAQAAAAAAgBQABAAAAgBQAAAAAAgBQAAAAAAgBQgBAAAAgBQAAAAgBgBQAAAAgBAAIgFgBIgJgDQgDgCAAgEQAAgEADgDQADgCAGAAQAFAAADACQAEADAAAEIgFAAQAAAAAAgBQAAAAgBgBQAAAAAAAAQgBgBAAAAQgCgCgDAAIgGABQAAAAgBABQAAAAAAABQAAAAgBABQAAAAAAABQAAAAAAABQABAAAAAAQAAABABAAQAAAAABABIAFABIAJACQAEACAAAFQAAAEgEADQgDACgGAAQgGAAgDgDgABLjMQgEgFAAgHQAAgHAEgEQAEgEAHAAQAGAAAFAEQAEAEAAAHQAAAHgEAFQgFAEgGAAQgHAAgEgEgABOjgQgCAEAAAEQAAAFACAEQADADAFAAQAEAAADgDQADgEAAgFQAAgEgDgEQgDgDgEAAQgFAAgDADgAgMjLQgEgEAAgHIAAgRIAFAAIAAARQAAAKAIAAQADAAADgDQACgDAAgGIAAgPIAFAAIAAAfIgEAAIgBgEQgDAEgGAAQgFAAgDgDgAiDjMQgEgFAAgHQAAgHAEgEQAEgEAHAAQAGAAAFAEQAEAEAAAHQAAAHgEAFQgFAEgGAAQgHAAgEgEgAiAjgQgCAEAAAEQAAAFACAEQADADAFAAQAEAAADgDQADgEAAgFQAAgEgDgEQgDgDgEAAQgFAAgDADgAjDjKQgEgDAAgEQAAgJANAAIAJAAIAAgCQAAgDgCgCQgCgCgEAAQgDAAgCACQgBAAAAAAQgBABAAAAQAAABAAAAQgBABAAAAIgFAAQABgEADgDQAEgCAFAAQAGAAADADQAEACAAAGIAAANQAAABAAAAQAAAAAAABQABAAAAAAQAAAAABAAIABAAIAAAFIgCAAQgGAAAAgFQgEAFgGAAQgFAAgDgCgAjCjRQAAAAAAABQABABAAAAQAAABAAAAQABAAAAABIAFABQAFAAACgCQADgDAAgEIAAgBIgKAAQgHAAAAAFgAjjjMQgEgEAAgHQAAgIAEgEQAEgEAHAAQAGAAADADQAEADAAAFIgFAAQgBgHgHAAQgEAAgDADQgDAEAAAFQAAAFADADQACADAFAAQADAAACgCQADgCAAgDIAFAAQAAAFgEADQgEADgFAAQgHAAgEgEgAkEjLQgDgEAAgHIAAgRIAFAAIAAARQAAAKAIAAQAEAAACgDQADgDAAgGIAAgPIAEAAIAAAfIgEAAIAAgEQgEAEgGAAQgGAAgDgDgAknjMQgEgEAAgIQAAgHAEgEQAEgEAGAAQAIAAADAFIAAgQIAFAAIAAAqIgFAAIAAgFQgEAFgHAAQgGAAgEgEgAkkjgQgCADAAAFQAAAFACAEQADADAFAAQAEAAADgDQADgEAAgEQAAgFgDgEQgDgDgEAAQgFAAgDADgAlJjMQgEgFAAgHQAAgHAEgEQAEgEAHAAQAGAAAEAEQAEAEAAAGIAAACIgYAAIAAABQAAAEADADQADADAEAAQADAAACgCQADgCABgDIAFAAQgBAFgEADQgEADgFAAQgHAAgEgEgAk1jbQgBgEgCgCQgDgCgDAAQgEAAgCACQgDADgBADIATAAIAAAAgAmOjMQgEgFAAgHQAAgHAEgEQAEgEAHAAQAGAAAFAEQAEAEAAAHQAAAHgEAFQgFAEgGAAQgHAAgEgEgAmLjgQgCAEAAAEQAAAFACAEQADADAFAAQAEAAADgDQADgEAAgFQAAgEgDgEQgDgDgEAAQgFAAgDADgAnPjLQgEgCAAgFIAFAAQABACACACQACACAEAAIAFgBQABgBAAAAQABAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQgBAAAAgBQgBAAAAAAIgGgBIgIgDQgEgCAAgEQAAgEADgDQAEgCAFAAQAFAAAEACQADADAAAEIgFAAQAAAAAAgBQAAAAAAgBQAAAAgBAAQAAgBgBAAQgCgCgDAAIgFABQgBAAAAABQAAAAgBABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAAAQABABAAAAQABAAAAABIAGABIAIACQAEACAAAFQAAAEgDADQgEACgFAAQgGAAgEgDgAoWjKQgDgDAAgEQAAgJAMAAIAJAAIAAgCQAAgDgCgCQgCgCgDAAQgEAAgCACQAAAAgBAAQAAABAAAAQgBABAAAAQAAABAAAAIgFAAQAAgEAEgDQADgCAGAAQAGAAADADQADACAAAGIAAANQAAABAAAAQABAAAAABQAAAAAAAAQABAAAAAAIACAAIAAAFIgDAAQgFAAAAgFQgEAFgHAAQgFAAgDgCgAoUjRQAAAAAAABQAAABAAAAQABABAAAAQAAAAABABIAFABQAEAAADgCQACgDAAgEIAAgBIgJAAQgHAAAAAFgApVjMQgEgFAAgHQAAgHAEgEQAEgEAGAAQAHAAADAEQAEAEABAGIgBACIgXAAIAAABQAAAEACADQADADAEAAQAEAAACgCQACgCABgDIAFAAQgBAFgDADQgEADgFAAQgHAAgEgEgApCjbQAAgEgDgCQgCgCgEAAQgDAAgDACQgDADAAADIASAAIAAAAgAqKjKQgDgDAAgEQAAgJAMAAIAJAAIAAgCQAAgDgCgCQgCgCgDAAQgEAAgCACQAAAAgBAAQAAABAAAAQgBABAAAAQAAABAAAAIgFAAQAAgEAEgDQADgCAGAAQAGAAADADQADACAAAGIAAANQAAABAAAAQABAAAAABQAAAAAAAAQABAAAAAAIACAAIAAAFIgDAAQgFAAAAgFQgEAFgHAAQgFAAgDgCgAqIjRQAAAAAAABQAAABAAAAQABABAAAAQAAAAABABIAFABQAEAAADgCQACgDAAgEIAAgBIgJAAQgHAAAAAFgArqjLQgEgCAAgFIAFAAQAAACACACQADACADAAIAGgBQAAgBABAAQAAAAAAgBQABAAAAgBQAAAAAAgBQAAAAAAgBQgBAAAAgBQAAAAgBgBQAAAAgBAAIgFgBIgJgDQgDgCAAgEQAAgEADgDQADgCAGAAQAFAAADACQAEADAAAEIgFAAQAAAAAAgBQAAAAgBgBQAAAAAAAAQgBgBAAAAQgCgCgDAAIgGABQAAAAgBABQAAAAAAABQAAAAgBABQAAAAAAABQAAAAAAABQABAAAAAAQAAABABAAQAAAAABABIAFABIAJACQAEACAAAFQAAAEgEADQgDACgGAAQgGAAgDgDgAEajIIAAgqIAFAAIAAAqgAEPjIIAAgRQAAgKgIAAQgFAAgCADQgCADAAAFIAAAQIgFAAIAAgfIAEAAIABAEQADgEAHAAQAFAAADADQAEAEAAAHIAAARgAARjIIAAgfIAEAAIABAFQACgFAHAAIABAAIAAAFIgCAAQgFAAgCADQgBADAAAEIAAAQgAhNjIIAAgRQAAgKgJAAQgEAAgCADQgDADAAAFIAAAQIgFAAIAAgfIAEAAIABAEQADgEAHAAQAGAAADADQADAEAAAHIAAARgAiSjIIAAgfIAFAAIAAAfgAibjIQgEAAgCgCQgCgCAAgEIAAgSIgGAAIAAgFIAGAAIAAgIIAFAAIAAAIIAIAAIAAAFIgIAAIAAASIABACIACABIAFAAIAAAFgAlvjIIAAgfIAEAAIABAFQADgFAGAAIACAAIAAAFIgDAAQgEAAgCADQgCADAAAEIAAAQgAmijIIAAgaIgGAAIAAgFIAGAAIAAgDQAAgEACgCQACgCAEAAIAFAAIAAAEIgFAAQgBAAAAAAQgBABAAAAQgBABAAAAQAAABAAABIAAADIAIAAIAAAFIgIAAIAAAagAndjIIAAgfIAFAAIAAAfgAn4jIIAAgqIAFAAIAAAqgAojjIIAAgfIAFAAIAAAfgAo3jIIAAgfIAEAAIABAFQADgFAGAAIACAAIAAAFIgDAAQgEAAgCADQgCADAAAEIAAAQgApijIQgEAAgCgCQgCgCAAgEIAAgSIgFAAIAAgFIAFAAIAAgIIAFAAIAAAIIAIAAIAAAFIgIAAIAAASIABACIADABIAFAAIAAAFgAqXjIIAAgSQAAgJgHAAQgEAAgCADQgDADAAAEIAAARIgEAAIAAgSQAAgJgIAAQgEAAgCADQgCADAAAFIAAAQIgFAAIAAgfIAEAAIABAEQADgEAGAAQAHAAADAGQADgGAHAAQAFAAADADQAEADAAAHIAAASgAr4jIIAAgfIAFAAIAAAfgAsDjIIAAgRQAAgKgJAAQgEAAgCADQgDADAAAFIAAAQIgFAAIAAgqIAFAAIAAAQQADgFAHAAQAGAAADADQAEAEAAAHIAAARgAsxjIIAAglIgOAAIAAgFIAhAAIAAAFIgOAAIAAAlgAiSjtIgBgCIABgCIADgBIACABIABACIgBACIgCABIgDgBgAndjtIgBgCIABgCIADgBIACABIABACIgBACIgCABIgDgBgAojjtIgBgCIABgCIACgBIACABIABACIgBACIgCABIgCgBgAr4jtIgBgCIABgCIACgBIACABIABACIgBACIgCABIgCgBg");
	this.shape.setTransform(43.125,-21.325);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.code_mc, new cjs.Rectangle(-42.1,-49,181.1,55.4), null);


(lib.branding_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#B7B6BB","#A8A4B1","#8C86A0","#787093","#675D87","#5C4F80","#55477D","#554582"],[0,0.051,0.141,0.251,0.361,0.498,0.671,1],-24.6,0,248.2,0).s().p("Ai9AoQgkAAAAgoQAAgnAkgBIF6AAQAkABAAAnQAAAogkAAg");
	this.shape.setTransform(-113.8,0);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#B7B6BB","#A8A4B1","#8C86A0","#787093","#675D87","#5C4F80","#55477D","#554582"],[0,0.051,0.141,0.251,0.361,0.498,0.671,1],-81.1,0,191.6,0).s().p("Ai8AoQgkAAAAgoQAAgnAkgBIF5AAQAkABAAAnQAAAogkAAg");
	this.shape_1.setTransform(-57.275,0);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#B7B6BB","#A8A4B1","#8C86A0","#787093","#675D87","#5C4F80","#55477D","#554582"],[0,0.051,0.141,0.251,0.361,0.498,0.671,1],-139.2,0,133.6,0).s().p("Ai8AoQgkAAAAgoQAAgnAkgBIF5AAQAkABAAAnQAAAogkAAg");
	this.shape_2.setTransform(0.825,0);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["#B7B6BB","#A8A4B1","#8C86A0","#787093","#675D87","#5C4F80","#55477D","#554582"],[0,0.051,0.141,0.251,0.361,0.498,0.671,1],-195.7,0,77,0).s().p("Ai8AoQgkAAAAgoQAAgnAkgBIF6AAQAjABABAnQgBAogjAAg");
	this.shape_3.setTransform(57.35,0);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.lf(["#B7B6BB","#A8A4B1","#8C86A0","#787093","#675D87","#5C4F80","#55477D","#554582"],[0,0.051,0.141,0.251,0.361,0.498,0.671,1],-252.2,0,20.5,0).s().p("Ai8AoQgkAAAAgoQAAgnAkgBIF5AAQAkABAAAnQAAAogkAAg");
	this.shape_4.setTransform(113.875,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.branding_mc, new cjs.Rectangle(-136.3,-4,272.70000000000005,8.1), null);


(lib.br = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#EEEEEE").s().p("AhjBkIAAjHIDHAAIAADHg");
	this.shape.setTransform(10,10);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.br, new cjs.Rectangle(0,0,20,20), null);


(lib.kv_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// timeline functions:
	this.frame_389 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(389).call(this.frame_389).wait(1));

	// Layer_1
	this.instance = new lib.kv_inner_mc();

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:1.1,scaleY:1.1},389).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-352,-528,704,1056);


// stage content:
(lib.index = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {frame2:27,frame3:62};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0,26,61,209];
	// timeline functions:
	this.frame_0 = function() {
		this.kv_mc.gotoAndPlay(1);
	}
	this.frame_26 = function() {
		var _this = this;
		this.stop();
		setTimeout(
			function () {
				_this.gotoAndPlay('frame2');
			}, 3500
		)
	}
	this.frame_61 = function() {
		var _this = this;
		this.stop();
		setTimeout(
			function () {
				_this.gotoAndPlay('frame3');
			},3500
		)
	}
	this.frame_209 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(26).call(this.frame_26).wait(35).call(this.frame_61).wait(148).call(this.frame_209).wait(1));

	// border
	this.instance = new lib.br();
	this.instance.setTransform(319.5,240.05,0.05,24.999,0,0,0,10,10);

	this.instance_1 = new lib.br();
	this.instance_1.setTransform(0.5,240.05,0.05,24.999,0,0,0,10,10);

	this.instance_2 = new lib.br();
	this.instance_2.setTransform(160,479.5,17.001,0.05,0,0,0,10,10);

	this.instance_3 = new lib.br();
	this.instance_3.setTransform(160,0.5,17.001,0.05,0,0,0,10,10);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_3},{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).wait(210));

	// s6
	this.instance_4 = new lib.s6_mc();
	this.instance_4.setTransform(151.5,129.5);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(81).to({_off:false},0).to({y:79.5,alpha:1},15,cjs.Ease.quadOut).wait(114));

	// s5
	this.instance_5 = new lib.s5_mc();
	this.instance_5.setTransform(151.5,129.5);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(46).to({_off:false},0).to({y:79.5,alpha:1},15,cjs.Ease.quadOut).to({y:39.5,alpha:0},15,cjs.Ease.quadInOut).wait(134));

	// s4
	this.instance_6 = new lib.s4_mc();
	this.instance_6.setTransform(151.5,129.5);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(12).to({_off:false},0).to({y:79.5,alpha:1},14,cjs.Ease.quadOut).to({y:39.5,alpha:0},15,cjs.Ease.quadInOut).wait(169));

	// branding_mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("EgcHAh9IAAsgMA4PAAAIAAMgg");
	var mask_graphics_3 = new cjs.Graphics().p("EgcHAh9IAAsgMA4PAAAIAAMgg");
	var mask_graphics_6 = new cjs.Graphics().p("EgcHAh9IAAsgMA4PAAAIAAMgg");
	var mask_graphics_9 = new cjs.Graphics().p("EgcHAh9IAAsgMA4PAAAIAAMgg");
	var mask_graphics_12 = new cjs.Graphics().p("EgcHAh9IAAsgMA4PAAAIAAMgg");
	var mask_graphics_15 = new cjs.Graphics().p("EgcHAh9IAAsgMA4PAAAIAAMgg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:-165,y:217.275}).wait(3).to({graphics:mask_graphics_3,x:-105,y:217.275}).wait(3).to({graphics:mask_graphics_6,x:-48,y:217.275}).wait(3).to({graphics:mask_graphics_9,x:11,y:217.275}).wait(3).to({graphics:mask_graphics_12,x:66,y:217.275}).wait(3).to({graphics:mask_graphics_15,x:160,y:217.275}).wait(195));

	// branding
	this.instance_7 = new lib.branding_mc();
	this.instance_7.setTransform(160.25,390.1);

	var maskedShapeInstanceList = [this.instance_7];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(210));

	// ref_code
	this.instance_8 = new lib.code_mc();
	this.instance_8.setTransform(46.95,469.3);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(9).to({_off:false},0).to({alpha:1},9,cjs.Ease.quadInOut).wait(192));

	// logo
	this.instance_9 = new lib.logo();
	this.instance_9.setTransform(249.5,513.45);

	this.timeline.addTween(cjs.Tween.get(this.instance_9).to({y:453.45},14,cjs.Ease.quadInOut).wait(196));

	// brand
	this.instance_10 = new lib.white_bg();
	this.instance_10.setTransform(160,526.55);

	this.timeline.addTween(cjs.Tween.get(this.instance_10).to({y:456.05},14,cjs.Ease.quadInOut).wait(196));

	// kv
	this.kv_mc = new lib.kv_mc();
	this.kv_mc.name = "kv_mc";
	this.kv_mc.setTransform(160,240,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.kv_mc).wait(210));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(140,230.1,200,336.5);
// library properties:
lib.properties = {
	id: 'A7AE48A664DE43B5BEC4BBCC86599430',
	width: 320,
	height: 480,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"kv.jpg", id:"kv"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['A7AE48A664DE43B5BEC4BBCC86599430'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;